superhero-com/superhero-wallet

- package-lock.json
- package.json
- src/popup/locales/en.json
- src/popup/router/pages/Retip.vue
- src/popup/router/routes.js
- tests/pages/index.html
Callbacks names inspired by http://x-callback-url.com/specifications/
> Add Retip page

- src/popup/router/pages/ImportAccount.vue
- src/popup/router/pages/Names.vue
> Trim spaces in seed and claiming .chain name

- src/popup/router/pages/Receive.vue
> White border to QR code for easier detection

- package-lock.json
- src/popup/router/pages/Send.vue
- src/popup/router/pages/SignTransaction.vue
- src/popup/router/pages/TipPage.vue
- src/popup/utils/helper.js
* Use sdk amount-formatter to convert to AE and Aettos
> Fix sending large amounts from withdraw page and use sdk to convert amounts

- .travis.yml
- scripts/before-deploy.sh
- webpack.config.js
I have already added $GITHUB_TOKEN and $CNAME=mobile.z52da5wt.xyz to Travis
> Build web version to GitHub pages

- src/popup/router/pages/TipPage.vue
> Check if url is verified rather the hostname

- src/popup/router/components/SidebarMenu.vue
- tests/e2e/integration/menu.js
> Remove duplicate links

- package-lock.json
- package.json
- src/popup/router/components/UserAvatar.vue
- src/popup/router/pages/Names.vue
- src/popup/utils/constants.js
I think backend endpoint for serving avatars should be changed either to return default identicon when no avatar, or return response by which extension can decide whether to use identicon
> Add identicon as default avatar

- .travis.yml
- scripts/deploy-stage.sh
After build Travis will add a comment to the last commit with a link to the deployed version
> travis: Enable per-branch deployment

- src/mixins/removeAccount.js
- src/popup/App.vue
- src/popup/locales/en.json
- src/popup/router/components/Modal.vue
- src/popup/router/components/Modals/ConfirmModal.vue
- src/popup/router/components/Modals/ConfirmTip.vue
- src/popup/router/components/SidebarMenu.vue
- src/popup/router/modals.js
- src/popup/router/pages/Settings.vue
- src/popup/router/routes.js
- src/store/index.js
- src/store/plugins/persistState.js
> Remove account

- src/popup/locales/en.json
- src/popup/router/components/TransactionItem.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/TipPage.vue
- tests/e2e/integration/tip.js
- tests/e2e/support/commands.js
* Tip URL field editable by default. Fixes #181 
* Adjust tests to changes
> Tip URL field editable by default

- src/popup/App.vue
- src/popup/router/components/TransactionFilters.vue
> TransactionFilters: Fix positioning

- src/background.js
- src/lib/redirect-chain-names.js
- src/lib/rpcWallet.js
- src/notifications.js
Ref: #184. Not sure if this pr will fix the problem cause I was not able to reproduce it, but made some optimizations in background script which maybe can stop slowing down page load
> Potential fix of blocked page load

- package-lock.json
- package.json
- src/background.js
- src/inject.js
- src/lib/background-utils.js
- src/lib/logger.js
- src/lib/request.js
- src/lib/rpcWallet.js
- src/lib/tip-claim-relay.js
- src/lib/wallet.js
- src/popup/App.vue
- src/popup/locales/en.json
- src/popup/popup.js
- src/popup/router/components/ClaimTips.vue
- src/popup/router/pages/AboutSettings.vue
- src/popup/router/pages/CommentNew.vue
- src/popup/router/pages/Names.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Settings.vue
- src/popup/router/pages/SignTransaction.vue
- src/popup/router/pages/SuccessTip.vue
- src/popup/router/pages/TipPage.vue
- src/store/actions.js
- src/store/index.js
- src/store/mutations.js
- src/store/plugins/persistState.js
* Donate error reports
* Logger class
* Global error handlers
* Log errors when claim, tip, retip, send comment, etc...
* Refactor phising message listener, because of error in Firefox
> Errors log

- src/lib/wallet.js
- src/popup/App.vue
- Fix .chain name not appearing initially after import wallet
Watcher for logged in:
- if logged call `init`
- if not logged clean poll interval
> Fix .chain name not appearing initially after import wallet

- src/popup/router/components/Input.vue
Was removed in https://github.com/aeternity/superhero-wallet/pull/217/files#diff-63a43df2db10d1cb53251bfe941d21edL2, breaks the part of #216 
please, resolve conflicts more accurate
> Input: Revert accidentally removed class

- src/lib/background-utils.js
- src/lib/logger.js
- src/lib/request.js
- src/lib/tip-claim-relay.js
- src/lib/wallet.js
- src/manifest.js
- src/popup/popup.js
- src/popup/router/pages/ClaimTips.vue
- src/popup/router/pages/CommentNew.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/SignTransaction.vue
- src/popup/router/pages/SuccessTip.vue
- src/popup/router/pages/Tip.vue
- src/popup/utils/openUrl.js
- webpack.config.js
I have not reviewed #208 in time, but I see some issues there:
- would be better to use global error handling in vue components than explicitly call $logError
- not necessary to preserve action name, because it is easily can be extracted from stack trace + map files like in this tutorial: https://medium.com/taskworld-tech/tracking-down-an-error-from-a-minified-production-stack-trace-7a7c7b812d55
- reduce the amount of Logger.write calls
- proposing to save platform as it is
and some other minor changes.
> Refactor logging

- src/lib/tip-claim-relay.js
> Text replace for no-zero amount claims

- src/popup/router/pages/Names.vue
- src/popup/router/pages/SignTransaction.vue
PS: I think Names.vue and SignTransaction.vue need to be refactored at some point, because is very messy there.
> Set pointer after name claim

- config.xml
- package-lock.json
- package.json
This fixes a url typo in the topup page.
> Release 0.0.24

- src/lib/backend.js
- src/popup/router/pages/CommentNew.vue
- tests/pages/index.html
> Add parentId param to comment endpoint

- src/background.js
- src/inject.js
- src/manifest.js
- src/popup/router/pages/Tip.vue
* Remove lsroute in Tip page when tip is from popup
* If extension installed set click event of tip link to open tip popup
* Send message form content to backround for tip popup
* Extract method in backgoround script for opening tip popup for both context tip and tip widget
> Handle tip widget click and open popup

- src/lib/logger.js
- src/lib/redirect-chain-names.js
- src/popup/router/components/Modals/ErrorLog.vue
* Check if there is error in ErrorLog modal before show message
* unhandledrejection listener check if reason type is string
* unhandledrejection listener if reason is WebAssembly error return and log error
* Handle unhandled exception in redirect chain names
> Fix showing error donation popup when open extension

- src/lib/logger.js
- src/popup/App.vue
- src/popup/locales/en.json
- src/popup/router/components/Modals/ErrorLog.vue
- src/popup/router/pages/AboutSettings.vue
- src/popup/router/pages/DonateError.vue
* Remove button from help page
* Send report to backend
* Show modal when report send
* Show modal when report not send
> Send error report to backend

- src/lib/backend.js
- src/lib/logger.js
- src/store/actions.js
Fixes for problems donated from users with donate error functionality.
> Handle reason of backend fail request, avoid NavigationDuplicated exception in logger

- tests/e2e/integration/about.js
- tests/e2e/integration/account.js
- tests/e2e/integration/aex2-popups.js
- tests/e2e/integration/aex2.js
- tests/e2e/integration/amount-send.js
- tests/e2e/integration/generate.js
- tests/e2e/integration/import.js
- tests/e2e/integration/menu.js
- tests/e2e/integration/networks.js
- tests/e2e/integration/notifications.js
- tests/e2e/integration/terms.js
- tests/e2e/integration/tip.js
- tests/e2e/integration/top-up.js
- tests/e2e/integration/transactions.js
- tests/e2e/integration/withdraw.js
- tests/e2e/support/commands.js
Accelerated tests by ~4 minutes out of ~9
> Refactor e2e tests

- src/popup/router/pages/Tip.vue
- tests/pages/index.html
> tip deeplink: Add message and amount params

- src/popup/locales/en.json
- src/popup/router/pages/Address.vue
- src/popup/router/routes.js
- tests/pages/index.html
The template syntax is inspired by https://en.wikipedia.org/wiki/URL_Template
> Expose current address through deeplink

- src/background.js
- src/inject.js
- src/phishing/App.vue
- src/popup/utils/connection.js
* Fix error Could not establish connection. Receiving end does not exist.
* Fix problem on Firefox with opening popup and then extension
> Fix donated errors

- package-lock.json
- package.json
- src/manifest.js
Also, I have made [a PR to the upstream repository](https://github.com/DiceBear/avatars/pull/73) that is already merged 🎉
closes #324
> Fix unsafe-eval issue related to avatars package

- src/popup/utils/connection.js
- src/store/actions.js
As I know, it works in the same way under the hood
> connection: Remove unnecessary try/catch

- src/background.js
- src/inject.js
* Handle click events from buttons that are created dynamically - not on page load
This pr depends on https://github.com/aeternity/superhero-button/pull/10
> Improve handle click of tip widget button

- package.json
> Change stylelint path

- src/background.js
- src/inject.js
Ref: https://github.com/aeternity/superhero-button/pull/10
> Adjust selector of superhero button to changes

- src/popup/router/pages/PrivacyPolicy.vue
- src/popup/router/pages/TermsOfService.vue
- src/popup/utils/openUrl.js
> Fix link in Terms and Privacy pages

- src/popup/router/pages/AboutSettings.vue
- webpack.config.js
> Add commitHash into about page

- src/popup/locales/en.json
> Text changes

- src/popup/router/components/Header.vue
> Header: Do not push the same route

- src/popup/router/pages/Receive.vue
- src/popup/utils/constants.js
> Remove universe store link

- src/popup/router/pages/Account.vue
- src/popup/router/pages/ImportAccount.vue
- src/popup/router/pages/SecuritySettings.vue
> Leave backup notification visible until user backs up their seed

- src/lib/rpcWallet.js
closes https://github.com/aeternity/superhero-ui/issues/434
ref https://github.com/aeternity/aepp-sdk-js/pull/1056
Manually dispatching of the onDisconnect to actually have it triggered, is planned to be investigated and fix on the sdk side.
> Adjust logout

- src/store/index.js
- src/store/plugins/persistState.js
It is blocking me from resetting localStorage of web version using dev tools. Is it used somewhere here? It was needed in the base aepp, and I assume it was just copy-pasted to wallet.
> Remove state sync between instances

- src/lib/wallet.js
- src/mixins/removeAccount.js
Need to be able to connect to Governance aepp in superhero-ui: https://github.com/aeternity/superhero-ui/pull/528#issuecomment-652651288
> Connect to parent subframes

- src/content-scripts/twitter.js
Fixes 1 more issue with twitter button styles
> twitter.js: Refactor button styles, fix padding absence

- src/content-scripts/twitter.js
I came to this while reviewing #433. The changes look obvious, but I have not tested them.
> twitter tip button: Avoid extra eslint-disable

- src/popup/router/index.js
- src/popup/router/pages/ImportAccount.vue
- src/popup/router/pages/Intro.vue
- src/store/index.js
- src/store/mutations.js
> Persist login target location

- config.xml
- package-lock.json
- package.json
- src/popup/utils/index.js
> Release 0.3.2: Fix date formatting

- src/popup/utils/constants.js
- tests/aepp/App.vue
- tests/e2e/integration/transactions.js
> Use aeternity.io instead of aeternal.io

- src/store/actions.js
- src/store/plugins/names.js
> Use middleware instance instead of direct fetching

- src/mixins/deeplinkApi.js
- src/popup/router/pages/Address.vue
- src/popup/router/pages/CommentNew.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/SignMessage.vue
- src/popup/router/pages/Tip.vue
needed for https://github.com/aeternity/superhero-button/pull/24
> Tip: Redirect to callback url if it provided

- src/lib/wallet.js
- src/popup/locales/cn.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/popup/router/components/CheckBox.vue
- src/popup/router/pages/Names/List.vue
- src/popup/utils/constants.js
- src/store/plugins/names.js
> Add auto-extending of names

- src/icons/checkbox-checked.svg
- src/icons/checkbox-unchecked.svg
- src/icons/iframe/checkbox-checked.svg
- src/icons/iframe/checkbox-unchecked.svg
- src/popup/router/components/CheckBox.vue
- src/popup/router/pages/Index.vue
- src/popup/router/pages/Intro.vue
> Change checkbox-unchecked icons color

- src/popup/utils/helper.js
fixes #520 
It takes significant amount of time to actually show the confirmation popup, my suggestion that [two seconds](https://github.com/aeternity/superhero-ui/blob/1fd0c075441edbe2988fdfd6f70d0f8985f2984a/src/utils/aeternity.js#L72) is not enough to actually proceed with the extension wallet
special thanks to @etharner, we eventually found out the problem
> Fix defaultNetworks issue

- src/popup/router/pages/Networks.vue
> Networks.vue: Delete network before selecting new one

- src/lib/wallet.js
original issue: https://github.com/aeternity/jitsi-meet/issues/240
Before this change wallet was trying to connect to a new frame two times: immediately and after 3 seconds for the case, when aepp has no enough time to initialize after opening. For some reason, our fork of Jitsi Meet in some cases can't initialize in time.
I assume that initialization time heavily depends on the performance and internet connection quality of the end-user. So, instead of just to increase the timeout I'm proposing a more durable connection approach to a new frame: try to connect immediately and then poll frame until it disappears from DOM or sends any response.
> hotfix: Poll aepps in reverse iframe

- src/popup/router/pages/Names/Details.vue
- src/store/plugins/names.js
> Fix names/setDefault

- src/common/variables.scss
- src/lib/rpcWallet.js
- src/lib/wallet.js
- src/popup/locales/en.json
- src/popup/router/components/CheckBox.vue
- src/popup/router/components/RangeInput.vue
- src/popup/router/components/SidebarMenu.vue
- src/popup/router/modals.js
- src/popup/router/pages/PermissionsSettings.vue
- src/popup/router/pages/Popups/MessageSign.vue
- src/popup/router/routes/index.js
- src/popup/router/routes/web-iframe-popups.js
- src/popup/utils/constants.js
- src/store/getters.js
- src/store/index.js
- src/store/modules/permissions.js
- src/store/plugins/account.js
> Add confirmation settings for popups

- tests/e2e/integration/account.js
- tests/e2e/integration/aex2-popups.js
- tests/e2e/integration/amount-send.js
- tests/e2e/integration/auth.js
- tests/e2e/integration/generate.js
- tests/e2e/integration/import.js
- tests/e2e/integration/index.js
- tests/e2e/integration/menu.js
- tests/e2e/integration/names.js
- tests/e2e/integration/networks.js
- tests/e2e/integration/other.js
- tests/e2e/integration/tip.js
- tests/e2e/integration/top-up.js
- tests/e2e/integration/withdraw.js
- tests/e2e/support/commands.js
Was using https://docs.cypress.io/guides/references/best-practices.html
> Improve tests

- tests/e2e/integration/withdraw.js
> [tests] withdraw: Change missed amount

- src/popup/router/components/Platforms.vue
- src/popup/router/pages/Index.vue
> Adjust styles in the Index page

- src/common/base.scss
- src/icons/filter-arrow.svg
- src/popup/locales/en.json
- src/popup/router/components/TransactionFilters.vue
- src/popup/router/pages/Transactions.vue
- src/store/actions.js
- fixes sorting by date (was broken because of the new middleware)
- allow sorting by date each tab
- proposing to rename "Received" to "Claimed" to make obvious that it is related only to tipping
> Refactor and fix bugs in transaction list

- src/popup/router/pages/Transactions.vue
The same was fixed before in:
https://github.com/aeternity/aepp-base/pull/1400
https://github.com/aeternity/superhero-ui/pull/692
> Transactions: Fix infinite load when page is zoomed

- .travis.yml
- scripts/before-deploy.sh
- tests/pages/index.html
@Liubov-crypto so, you can use [this link](https://feature-deeplink-test-page-artifacts.wallet.z52da5wt.xyz/artifacts/deeplink-test.html) to test deeplinks on mobile
> Add deeplink test page to artifacts

- src/lib/rpcWallet.js
- src/lib/wallet.js
- src/popup/router/pages/Names/Details.vue
- src/store/modules/permissions.js
- src/store/plugins/account.js
- src/store/plugins/names.js
> Fix aens errors

- src/popup/router/components/TransactionItem.vue
- src/store/getters.js
- tests/e2e/integration/transactions.js
What to test:
- ensure that nothing is broken in the transaction list and account page
> TransactionItem: Don't make extra requests to the node

- src/popup/locales/en.json
- src/popup/router/pages/Settings.vue
Closes #585.
Please correct wording if needed.
> permissions: Add panel to settings screen

- src/popup/router/pages/Names/List.vue
> List: prevent falling through checkbox in firefox

- src/popup/router/components/CheckBox.vue
- src/popup/router/pages/FungibleTokens/Deploy.vue
- src/popup/router/pages/Names/List.vue
- src/popup/router/pages/Networks.vue
- src/popup/router/pages/PermissionsSettings.vue
- src/popup/router/pages/Settings.vue
> Refactor CheckBox component

- src/lib/vuexRouterSync.js
- src/phishing/App.vue
- src/popup/App.vue
- src/popup/popup.js
- src/popup/router/components/PendingTxs.vue
- src/popup/router/components/RecentTransactions.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/store/actions.js
- src/store/index.js
- src/store/mutations.js
- src/store/plugins/pendingTransactionHandler.js
> Make pending transaction polling more accurate

- src/popup/router/pages/SecuritySettings.vue
> SecuritySettings: Remove usage of a non-existent component

- src/common/extension.scss
- src/popup/router/components/AmountSend.vue
- src/popup/router/components/Modals/ClaimSuccess.vue
- src/popup/router/pages/Intro.vue
- src/popup/router/pages/Receive.vue
- src/popup/router/pages/SecuritySettings.vue
related to https://github.com/aeternity/superhero-wallet/pull/614/commits/af99dfad2302c04c7fee50c1c0b36bb9f7a1e960
> Remove inline styles

- src/popup/router/components/Modal.vue
- src/popup/router/components/Modals/ClaimSuccess.vue
- src/popup/router/components/Modals/Confirm.vue
- src/popup/router/components/Modals/ConfirmRawSign.vue
- src/popup/router/components/Modals/ConfirmTip.vue
- src/popup/router/components/Modals/ConfirmTransactionSign.vue
- src/popup/router/components/Modals/Default.vue
- src/popup/router/components/Modals/ErrorLog.vue
- src/popup/router/components/Modals/QrCodeReader.vue
- src/popup/router/components/Modals/SignModal.scss
- src/popup/router/components/Modals/TipUrlStatus.vue
- tests/e2e/integration/withdraw.js
- tests/e2e/support/commands.js
this is related to fixing #622 
what to test: ensure that all modals work/look correctly
> Refactor Modal component

- src/popup/router/pages/Transactions.vue
> Transactions: Check need to fetch transactions if transactions or displayMode changes

- src/popup/router/components/NameRow.vue
- src/popup/router/pages/Names/Details.vue
> Fix address displaying on several screens

- src/lib/rpcWallet.js
- src/lib/wallet.js
- src/popup/router/pages/PermissionsSettings.vue
- src/popup/utils/constants.js
This is part of changes I've made for #584, closes #630.
> Fix message sign popups constantly appearing

- src/store/plugins/names.js
> Fetch prefered name

- .travis.yml
- scripts/before-deploy.sh
- add screenshots to artifacts to simplify test debugging in some cases
- deploys to staging even if tests fail, to simplify prototyping and so
> Travis build process improvements

- src/store/actions.js
> Fix sending an error report

- src/popup/router/pages/Send.vue
> Send: Trim entered address

- src/lib/wallet.js
- src/popup/router/components/Dropdown.vue
- src/popup/router/pages/Names/Details.vue
- src/popup/router/pages/Popups/SignTx.vue
- src/store/plugins/names.js
fixes #664,
part of #662 (add changes missed in #565/ proper showing of peding transactions time), *removed since @davidyuk made a separate [PR](#685)*
fix wording in Details component
> Refactoring

- src/popup/router/pages/Names/Details.vue
- src/store/plugins/names.js
> Refactor names

- src/popup/router/pages/PermissionsSettings.vue
closes #690 was broken in 770acec1f40e3874a480fa33d19ab338c679707e
> PermissionSettings: Simplify and fix validation

- src/popup/router/pages/Retip.vue
> Refactor amount validation in Retip page

- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/store/modules/fungibleTokens.js
- src/store/plugins/pendingTransactionHandler.js
- tests/e2e/integration/withdraw.js
Added the option to directly send fungible tokens to other addresses.
> Witdraw fungible tokens

- src/popup/router/components/Modals/QrCodeReader.vue
> QrCodeReader: Display Header menus

- src/popup/router/pages/Intro.vue
> Intro: Adjust markup

- src/popup/App.vue
- src/popup/router/components/AmountSend.vue
- src/popup/router/components/BalanceInfo.vue
- src/popup/router/components/FungibleTokens/TokensList.vue
- src/popup/router/components/InviteItem.vue
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
- src/popup/router/pages/Invite.vue
- src/popup/router/pages/Names/AuctionBid.vue
- src/popup/router/pages/Names/AuctionDetails.vue
- src/popup/router/pages/Names/AuctionList.vue
- src/popup/router/pages/PermissionsSettings.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/popup/utils/helper.js
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/plugins/observables.js
- tests/e2e/integration/amount-send.js
- tests/e2e/support/commands.js
fixes #646, #641
potential fix for #629
> Make topBlockHeight and balance observables

- src/popup/locales/cn.json
- src/popup/locales/de.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/popup/locales/fr.json
- src/popup/locales/it.json
- src/popup/locales/ru.json
- src/popup/router/components/AmountSend.vue
- src/popup/router/components/BalanceInfo.vue
- src/popup/router/components/SidebarMenu.vue
- src/popup/router/components/SignDetailsList.vue
- src/popup/router/components/Welcome.vue
- src/popup/router/pages/AboutSettings.vue
- src/popup/router/pages/Account.vue
- src/popup/router/pages/Intro.vue
- src/popup/router/pages/Names/AuctionBid.vue
- src/popup/router/pages/Names/AuctionDetails.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Settings.vue
> Remove appVue keys

- src/popup/router/components/Dropdown.vue
- src/popup/router/components/Modals/SignModal.scss
> Fix firefox design related issues

- src/popup/App.vue
- src/popup/locales/cn.json
- src/popup/locales/de.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/popup/locales/fr.json
- src/popup/locales/it.json
- src/popup/locales/ru.json
- src/popup/router/components/Header.vue
- src/popup/router/components/SidebarMenu.vue
- src/popup/router/pages/About.vue
- src/popup/router/pages/Index.vue
- src/popup/router/pages/LanguageSettings.vue
- src/popup/router/pages/Settings.vue
- src/popup/router/routes/index.js
- tests/e2e/integration/about.js
- tests/e2e/integration/auth.js
- tests/e2e/integration/index.js
- tests/e2e/integration/menu.js
- tests/e2e/integration/networks.js
- tests/e2e/integration/other.js
- tests/e2e/integration/terms.js
- tests/e2e/support/commands.js
> Make back button go up in the hierarchy

- src/lib/logger.js
> logger: Fix handling vue errors

- src/lib/initEnv.js
- src/popup/popup.js
- src/store/plugins/pendingTransactionHandler.js
> Wait pending transactions mined if sdk initialized

- src/popup/router/pages/Transactions.vue
fixes #579,
fixes #537,
part of #710
> Transactions: Load transactions only if previous are loaded

- src/popup/locales/en.json
- src/popup/router/pages/SuccessTip.vue
- src/popup/router/pages/Tip.vue
- tests/e2e/integration/amount-send.js
> Added a verbose validation for Tip component

- src/popup/router/components/Tour.vue
Make `previous` button work properly on each step, was broken in 691cfa3989d19a476d552438dd4d9bf6e19472c8
> Tour: Revert changes to propertires in steps

- src/popup/router/components/DetailsItem.vue
Introduced in #642,
part of #666
> DetailsItem: Keep items in wallet bounds

- src/popup/locales/en.json
- src/popup/router/components/InviteItem.vue
> Added indicator for copied address in invite links page

- src/lib/wallet.js
- src/popup/router/components/AmountSend.vue
- src/popup/router/components/BalanceInfo.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/store/actions.js
- src/store/modules/fungibleTokens.js
- src/store/plugins/observables.js
This is a temporary solution to handle the problem with #723 which prevents some of the functionality with Fungible Tokens in the wallet to work properly.
> Fungible Tokens: Middleware CORS issue workaround

- src/lib/logger.js
- src/popup/router/components/Modals/QrCodeReader.vue
missed in #725, should be included in release
> logger: Handle user rejection error

- src/popup/router/components/AmountSend.vue
- src/popup/router/components/BalanceInfo.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/store/plugins/observables.js
part of #754, fixes #753, fixes #752
> Make amount a string instead of BigNumber

- .github/workflows/main.yml
- .versionrc.js
- commitlint.config.js
- config.xml
- package-lock.json
- package.json
- general commit template: https://www.conventionalcommits.org/
- type explanation: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type
Use `npm run release` instead of `npm version <version number>` to bump a package version according to semver and to generate a CHANGELOG.md.
> Build changelog and lint commit messages

- src/popup/router/components/AccountInfo.vue
- src/styles/global.scss
> Fix chain name outside viewport

- src/popup/router/components/AccountInfo.vue
> Fix copy address not working

- src/popup/router/pages/Retip.vue
> Fix incorrect amount on retip success

- src/popup/router/components/InviteItem.vue
- src/popup/router/pages/Invite.vue
- src/popup/router/pages/PermissionsDetails.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/popup/utils/helper.js
- src/store/modules/fungibleTokens.js
- src/store/plugins/observables.js
closes #782, fixes #754, fixes #773
supersedes #774
**QA**
* All token balances displayed
* Balance sufficiency checks (Send/Tip/Retip/Invites/Permissions)
> Use BigNumber for token balances

- src/popup/router/components/AccountInfo.vue
Issue mentioned here: https://github.com/aeternity/superhero-wallet/pull/785#issuecomment-770913548
Introduced in #777
> Hide chain name scrollbars on Firefox

- config.xml
- package-lock.json
- package.json
- src/popup/router/components/Header.vue
> Fix broken header titles on iOS

- src/popup/router/components/AccountInfo.vue
Fix after reverting the global style hiding scrollbars #796
> Hide chain name scrollbar

- src/popup/router/pages/NotificationSettings.vue
- src/store/mutations.js
> Toggle showable types of notification properly

- src/popup/router/components/AccountInfo.vue
- src/popup/router/pages/Names/List.vue
- src/popup/utils/helper.js
> Make long names do not get out of the borders

- src/popup/router/components/NotificationItem.vue
> chore(notification-item): change word-break style

- package-lock.json
- package.json
https://www.npmjs.com/package/pre-commit
> Lint pre-commit hook

- package-lock.json
- package.json
> Revert "Lint pre-commit hook"

- src/popup/router/components/TransactionItem.vue
- src/popup/utils/helper.js
- src/store/actions.js
- src/store/plugins/names.js
> Fetch pending transactions

- package-lock.json
- package.json
- src/popup/App.vue
- src/popup/popup-firefox.html
- src/popup/popup.html
- src/popup/router/components/Button.vue
- src/popup/router/components/Header.vue
- src/popup/router/components/InviteItem.vue
- src/popup/router/components/Modal.vue
- src/popup/router/components/Modals/SignModal.scss
- src/popup/router/components/NameListHeader.vue
- src/popup/router/components/Textarea.vue
- src/popup/router/components/Tour.vue
- src/popup/router/components/Welcome.vue
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
- src/popup/router/pages/FungibleTokens/TokensPreview.vue
- src/popup/router/pages/ImportAccount.vue
- src/popup/router/pages/Index.vue
- src/popup/router/pages/Names/Claim.vue
- src/popup/router/pages/Networks.vue
- src/popup/router/pages/SuccessTip.vue
- src/styles/global.scss
- src/styles/typography.scss
- src/styles/variables.scss
> Apply some general rebranding

- .github/workflows/main.yml
> fix(ci): don't fetch develop if running tests on develop

- src/styles/global.scss
- src/styles/variables.scss
The portfolio button is not reachable due to a logo margins, fixes this as well
> Remove unused global styles

- src/styles/variables.scss
> Change background colors

- src/popup/router/components/Header.vue
- src/popup/router/components/TruncateMid.vue
- tests/e2e/integration/names.js
> fix: use TruncateMid only for custom titles

- .github/stale.yml
Add stale bot to close inactive PRs.
> Feat: Add Stale bot

- src/popup/router/components/Plate.vue
- src/popup/router/components/RecentTransactions.vue
- src/popup/router/pages/Account.vue
- tests/e2e/integration/names.js
fixes #897, related to #883
used in pages from new designs:
* home
* accounts
* payments
* transaction
* token
* tips
> Extract Plate component

- src/popup/router/components/BoxButton.vue
- src/popup/router/components/MenuCarousel.vue
- src/popup/router/pages/About.vue
- src/popup/router/pages/TermsOfService.vue
> refactor: keep only state in component data objects

- src/popup/router/pages/Receive.vue
> refact(receive): remove home button in favor of the back arrow

- src/popup/router/pages/Invite.vue
> refact(invites): show generated-invites section if invites exist

- tests/e2e/integration/top-up.js
> test(fix): use back button in top-up

- src/popup/router/pages/ImportAccount.vue
> fix: set formatted mnemonic phrase

- src/store/mutations.js
> fix(networks): make editing of networks reactive

- src/popup/router/components/BoxButton.vue
- src/popup/router/components/CheckBox.vue
- src/popup/router/components/DetailsItem.vue
- src/popup/router/components/Platforms.vue
- src/popup/router/components/RecentTransactions.vue
- src/styles/typography.scss
Make typography font same as in designs system
> Change typography fonts

- src/store/modules/invites.js
> fix(claim-links): use account getter instead of nonexistent account state

- webpack.config.js
@Liubov-crypto ensure that it doesn't break the injected tip button styles
> refactor(webpack): simplify path

- src/popup/router/components/TransactionItem.vue
- tests/e2e/integration/transactions.js
> refactor(tx-item): use RouterLink component

- src/popup/locales/en.json
- src/popup/router/components/NameRow.vue
- src/popup/router/pages/Names/List.vue
- src/store/plugins/names.js
part of #902,
propose to have an endpoint returning such info per account https://github.com/aeternity/ae_mdw/issues/157
> fix(names): remove obsolete removed state in names

- src/popup/App.vue
- src/popup/router/pages/Popups/AexPopup.scss
This PR fixes missed this bugs:
> Fix appearance bugs after general rebranding

- src/popup/router/components/AccountInfo.vue
- src/popup/router/components/CopyButton.vue
- src/popup/router/components/InviteItem.vue
https://github.com/aeternity/superhero-wallet/pull/951#discussion_r607898332
> refactor: handle clipboard copy success more accurately

- src/popup/router/components/PendingTxs.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/Send.vue
- src/popup/router/pages/Tip.vue
- src/store/getters.js
fixes issues related to pending transactions mentioned in https://github.com/aeternity/superhero-wallet/pull/957#issuecomment-815559362
> Fixes for pending transactions

- cypress.json
- scripts/build-zip.js
- src/manifest.js
- src/store/plugins/persistState.js
- tests/e2e/integration/other.js
- tests/e2e/integration/top-up.js
- tests/e2e/support/commands.js
- webpack.config.js
depends on #941 
This would simplify switching to vue/cli and also speed up a default `build` script
@Liubov-crypto, please ensure that the Firefox extension behaving as before
> Build a single extension version

- src/store/plugins/names.js
> fix(names): switch from deprecated profile endpoint

- src/popup/router/components/RecentTransactions.vue
- src/popup/router/pages/Transactions.vue
- src/store/actions.js
- src/store/mutations.js
> Limit recent transactions count

- src/lib/initEnv.js
- src/popup/App.vue
- src/popup/router/components/NodeConnectionStatus.vue
- src/popup/router/components/Platforms.vue
This PR fixes padding and height problems on Android and extensions.
Closes #975, #973.
> Fix height and padding problems

- src/popup/App.vue
- src/popup/router/routes/web-iframe-popups.js
- tests/e2e/integration/generate.js
This PR fixes this behaviour in web-iframe-popups:
> fix(web-iframe-popups): make iframe popups notRebranded

- src/popup/router/pages/Notifications.vue
> fix(notifications): use first name in the list if chainNames presented

- src/popup/router/pages/Accounts.vue
| before | after |
| ------ |  ---- |
| ![recording (13)](https://user-images.githubusercontent.com/482351/114991698-8ea4fd00-9ea2-11eb-9510-2a90e06b146a.gif)|![recording (12)](https://user-images.githubusercontent.com/482351/114992079-0541fa80-9ea3-11eb-876f-9a2e673ff7b6.gif)|
> refactor(accounts): use Plate component

- src/popup/App.vue
- src/popup/router/components/MenuCarousel.vue
- src/popup/router/components/NodeConnectionStatus.vue
- src/popup/router/pages/Intro.vue
- src/styles/mixins.scss
> refactor(scss): start to "use" instead of "import"

- src/popup/router/pages/TransactionDetails.vue
> fix(tx-details): keep header on top

- src/popup/router/components/AccountInfo.vue
removed in 7a954c6687aed1b5df642b95187cd70f2cfd7124,
mentioned here https://github.com/aeternity/superhero-wallet/pull/1016#issuecomment-822399009
https://vue-loader.vuejs.org/guide/scoped-css.html#also-keep-in-mind
> fix(styles): add proper styles for custom name input

- src/popup/utils/constants.js
related and may be a potentional fix for the #1024 
mentioned by @kenodressel
> Change testnet backend url

- src/popup/App.vue
- src/popup/router/index.js
- src/popup/router/pages/Accounts.vue
fixes:
* pages with different background color from header 
| before | after |
| ------ | ----- |
|![Screenshot 2021-04-15 at 15 21 23](https://user-images.githubusercontent.com/482351/114886597-58b73880-9e10-11eb-9441-5cf8fef2e584.png) | ![Screenshot 2021-04-15 at 15 21 35](https://user-images.githubusercontent.com/482351/114886696-6d93cc00-9e10-11eb-8bd0-36bef79d71f7.png)|
* overscroll (solution suggested here https://github.com/aeternity/superhero-wallet/pull/931#discussion_r613115772)
| before | after |
| ------ | ----- |
|<img width="391" alt="Screenshot 2021-04-15 at 13 12 08" src="https://user-images.githubusercontent.com/482351/114886802-88664080-9e10-11eb-9050-21e5fbff9830.png">| <img width="395" alt="Screenshot 2021-04-15 at 13 14 20" …
> Fix app background color

- src/popup/router/components/AmountSend.vue
- src/popup/router/components/InviteItem.vue
- src/popup/router/components/SignDetailsList.vue
- src/popup/router/pages/Invite.vue
> fix(invite): show correct token

- src/background/store.js
> fix(background): add missing getters

- src/popup/router/components/RecentTransactions.vue
> Change recent transactions on switching accounts

- tests/e2e/integration/aex2-popups.js
- tests/e2e/integration/aex2.js
- tests/e2e/integration/amount-input.js
- tests/e2e/integration/networks.js
- tests/e2e/integration/transaction-details.js
- tests/e2e/integration/transactions.js
- tests/e2e/integration/withdraw.js
- tests/e2e/support/commands.js
> Fix failing tests

- src/popup/router/pages/Notifications.vue
> Fix notifications displaying

- src/popup/router/components/Modals/QrCodeReader.vue
> fix(qr-code-reader): do not interact with header styles explicitly

- src/popup/locales/en.json
- src/popup/router/components/InviteItem.vue
- src/popup/router/pages/InviteClaim.vue
- src/store/modules/invites.js
> fix(invite-claim): update handleNotEnoughFoundsError

- src/popup/router/components/TabBar.vue
> fix(tab-bar): color home button area on iOS

- src/popup/router/index.js
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
- src/store/plugins/pendingTransactionHandler.js
- tests/e2e/integration/other.js
> fix(routes): fix tabs routes

- src/popup/router/routes/index.js
> fix(routes): enable props for PaymentsSend

- src/popup/locales/en.json
- src/popup/router/pages/PaymentsSend.vue
> refactor(payments-send): disable sending tokens to a name

- scripts/build-zip.js
- src/lib/logger.js
- src/popup/cameraPermission.js
- src/popup/router/components/Avatar.vue
- src/popup/router/components/Button.vue
- src/popup/router/components/CheckBox.vue
- src/popup/router/components/DetailsItem.vue
- src/popup/router/components/DetailsItemOld.vue
- src/popup/router/components/Dropdown.vue
- src/popup/router/components/FungibleTokens/TokensListItem.vue
- src/popup/router/components/InputField.vue
- src/popup/router/components/Modals/Confirm.vue
- src/popup/router/components/Modals/Default.vue
- src/popup/router/components/NameRow.vue
- src/popup/router/components/NotificationItem.vue
- src/popup/router/components/PanelItem.vue
- src/popup/router/components/Textarea.vue
- src/popup/router/components/TokenAmount.vue
- src/popup/router/components/Tour.vue
- src/popup/router/components/TransactionItem.vue
- src/popup/router/components/UrlStatus.vue
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
- src/popup/router/pages/Names/Details.vue
- src/popup/router/pages/Networks.vue
- src/popup/router/pages/PaymentsSend.vue
- src/popup/router/pages/PermissionsDetails.vue
- src/popup/router/pages/SuccessTip.vue
> Fix warnings

- src/popup/router/pages/Invite.vue
> fix(invite): set missing invite icon size

- src/popup/router/components/Header.vue
> fix(header): disallow title text wrapping

- src/popup/router/components/PendingTxs.vue
- src/store/actions.js
- src/store/getters.js
- tests/e2e/integration/other.js
We catched this because currently txs aren't mined on testnet and we have time to see this problem.
> fix(pending): fix duplicate pending transactions

- src/popup/router/components/SmallModal.vue
> fix(small-modal): fix mark as read unavailable for clicking

- src/popup/router/components/RecentTransactions.vue
- src/popup/router/pages/Account.vue
fixes #1084
| before | after |
| -------- | -------------- | 
| ![recording (18)](https://user-images.githubusercontent.com/482351/118612852-db903200-b7c6-11eb-8ef9-0485f174dc56.gif) | ![recording (17)](https://user-images.githubusercontent.com/482351/118612860-dd59f580-b7c6-11eb-9466-de6c5e5a23d8.gif) |
> fix(recent-txs): align empty and loading states

- src/popup/router/components/InviteItem.vue
- src/popup/router/pages/Invite.vue
- src/store/modules/invites.js
missed #1048
fixes issue originally posted here https://github.com/aeternity/superhero-wallet/pull/1097#pullrequestreview-665720654
> Got this error when creating an invite link and rejecting transaction (mainnet):
> ![when create an invite link and reject](https://user-images.githubusercontent.com/69896204/119167653-b7ec1680-ba68-11eb-9253-ed3785c58043.png)
>
> fix(invite): fix handleNotEnoughFoundsError parameters

- src/popup/router/pages/CommentNew.vue
> fix(comment-new): reload info on query change

- src/popup/router/components/AccountCard.vue
- src/popup/router/components/AccountInfo.vue
- src/popup/router/components/AccountSwitcher.vue
- src/popup/router/components/ButtonPlain.vue
- src/popup/router/components/CopyButton.vue
- src/popup/router/components/Header.vue
- src/popup/router/components/InviteItem.vue
- src/popup/router/components/Modal.vue
- src/popup/router/components/Modals/ConfirmTransactionSign.vue
- src/popup/router/components/SidebarMenu.vue
- src/popup/router/components/TabsMenu.vue
- src/popup/router/components/TransactionFilters.vue
- src/popup/router/pages/Intro.vue
- src/popup/router/pages/Networks.vue
- src/popup/router/pages/Notifications.vue
> refactor(global): use ButtonPlain component

- src/popup/router/components/Modals/ConfirmTransactionSign.vue
- src/store/getters.js
> feat(confirm-tx): show name fee token amount

- src/popup/router/components/Modal.vue
- src/popup/router/components/NodeConnectionStatus.vue
> feat: show node status in full screen modals

- src/popup/router/components/AccountSwitcher.vue
will solve the problem on phones
> fix(account): disable horizontal scrolling

- package-lock.json
- package.json
- src/popup/router/components/AccountInfo.vue
- src/popup/router/components/DetailsItem.vue
- src/popup/router/components/InfoGroup.vue
- src/styles/typography.scss
- src/styles/variables.scss
fix addres overflowing issue.
For example:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/120583637-fa065680-c471-11eb-9603-94c0f173713e.png)|![image](https://user-images.githubusercontent.com/9008074/120589423-2cb54c80-c47c-11eb-959d-71403409b2b3.png)|
> Fix address text overflow

- src/popup/router/components/Platforms.vue
> fix(platforms): change ios link from testflight to store

- src/popup/App.vue
- src/popup/router/components/AccountSwitcher.vue
> Fix horizontal scrolling

- src/popup/router/components/Modals/QrCodeReader.vue
Fixes lack of camera preview in Cordova
> fix(qr-code): inline transparent style to show preview in cordova

- src/popup/utils/helper.js
- src/store/plugins/observables.js
> refactor(observables): set all account balances to local storage

- src/store/plugins/observables.js
> fix(observables): use new balance storage structure

- src/popup/router/components/AccountItem.vue
- src/popup/router/components/Avatar.vue
- src/popup/router/components/SidebarMenu.vue
- src/styles/typography.scss
> AccountItem component

- src/store/plugins/fungibleTokens.js
> Use mdw endpoint for fungible tokens instead of backend

- src/popup/router/components/Modals/Default.vue
- src/popup/router/pages/Names/Claim.vue
fixes #1162
https://github.com/aeternity/aepp-sdk-js/issues/1246
> Fix broken modals

- src/popup/router/pages/PaymentsSend.vue
- tests/e2e/integration/withdraw.js
> feat(payments-send): drop trailing zeros from amount

- src/popup/router/pages/PaymentsSend.vue
- src/store/getters.js
> chore(pending-token-tx): show pending token tx immediately

- src/lib/logger.js
> chore(logger): don't show error modal by default on production

- src/popup/router/pages/FungibleTokens/TokenDetails.vue
| before | after |
| ------ | ----- |
|![Screenshot 2021-07-07 at 16 18 55](https://user-images.githubusercontent.com/482351/124767198-45fc5d80-df40-11eb-94b1-ec188deb3762.png) | ![Screenshot 2021-07-07 at 16 19 51](https://user-images.githubusercontent.com/482351/124767209-48f74e00-df40-11eb-8a7c-d1249f515795.png)|
> fix(token-details): fix header padding

- src/popup/router/components/RecentTransactions.vue
- src/popup/router/components/TransactionList.vue
- src/popup/utils/constants.js
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/modules/transactionCache.js
- src/store/plugins/chainListener.js
- tests/e2e/integration/networks.js
Disclaimer: 
This only works for a sample token: `Bitcoin` aka `ct_jzUHLhMK112thY2YkZb4tzgUHtYbtzqHyLZnEjxmKzsp88Hkt`
We will likely be able to scale it up but it would probably better to add an intermediary (external service) that filters the tx beforehand.
> feat(txlist): adds realtime capability via websocket

- src/popup/router/components/BalanceInfo.vue
One more fix which align dropdown properly
> fix(dropdown): fix dropdown align

- src/popup/router/components/TransactionList.vue
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
> fix(token-details): fix loader size in tx list

- src/popup/router/components/CheckBox.vue
- src/popup/router/pages/NotificationSettings.vue
> style(checkbox): update checkbox color

- src/background/deeplink-handler.js
- src/popup/router/components/InviteItem.vue
- src/popup/router/components/Platforms.vue
- src/popup/router/index.js
- src/popup/router/pages/PrivacyPolicy.vue
- src/popup/router/pages/TermsOfService.vue
- src/popup/utils/constants.js
> refactor(app-links): add app links for all platforms to constants

- src/store/actions.js
> Fix fetchTransactions

- src/popup/router/pages/Networks.vue
> Custom network default values

- src/popup/router/components/PendingTxs.vue
- src/popup/router/components/TransactionList.vue
- tests/e2e/integration/other.js
fixes #1142,
also fixing appearing of text that about empty list, when the transactions are not even start to fetch
> Fix pending transactions

- src/popup/router/components/Modals/Default.vue
- src/popup/router/pages/CommentNew.vue
- src/popup/router/pages/Names/Claim.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/TipsSend.vue
- src/popup/router/pages/TransferSend.vue
> refactor(modals): drop localization with dynamic keys

- src/popup/router/routes/index.js
fixes #1220 
https://github.com/pillarjs/path-to-regexp/issues/142#issuecomment-371027902
> feat(routes): add tip redirection

- src/popup/router/routes/index.js
based on https://github.com/aeternity/superhero-ui/blob/3ad2490571b7aa2c65a4e2fc56eab3464b5f40eb/src/router.js#L81-L84
supposed to fix #1220 
need to ensure that redirect works in Cordova
> feat: redirect only from /tip to /tips

- src/popup/router/components/TransactionOverview.vue
- src/popup/router/pages/Names/Details.vue
- src/store/migrations/04-add-names-new-fields.js
- src/store/migrations/index.js
- src/store/plugins/names.js
> feat: show chain name of other users

- src/popup/router/components/TransactionList.vue
- src/store/actions.js
fixes #1228
fixes #1211
fixes #1195
> Fixes for TransactionList

- README.md
Copy of #1246, but squashed and rebased on develop
Originally created by: James Kolonusz <jamesko@users.noreply.github.com>
> docs(readme): correct grammar and spelling

- src/popup/router/components/Header.vue
- src/popup/router/components/TabBar.vue
- src/popup/router/routes/index.js
- tests/e2e/integration/account.js
> Remove back button from main views

- src/popup/router/components/Overview.vue
fixes #1250
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/130160433-ad224c58-7fe9-498d-a0b9-c2a0b518cf0e.png)|![image](https://user-images.githubusercontent.com/9008074/130160417-7f8e0b91-8b37-4617-bbf2-25eef4ecbbcf.png)|
> fix(overview): avoid wrapping for chain names

- src/popup/router/components/NameItem.vue
> fix(name-item): set Pending svg size

- src/popup/router/components/TransactionList.vue
- src/popup/router/pages/PrivacyPolicy.vue
fixes #945,
originally created https://github.com/aeternity/superhero-wallet/pull/1093
> chore: <ul> and <ol> usage

- config.xml
> feat(mobile): lock orientation to portrait

- src/popup/locales/en.json
- src/popup/router/components/Modals/QrCodeReader.vue
> feat(qr-reader): open settings when camera not allowerd on mobile

- src/popup/router/components/Truncate.vue
This idea came while reviewing of #1262. If we don't want truncated element to scroll we can use this prop.
> feat(truncate): allow truncate to be fixed

- src/popup/router/pages/TransactionDetails.vue
> fix(tx-details): handle overflowing tip url

- src/popup/router/components/NameItem.vue
missed in #1169 in several rebases
> fix(name-item): call setAutoExtend action with proper params

- package-lock.json
- package.json
- src/lib/wallet.js
- src/popup/utils/constants.js
- src/store/modules/invites.js
> chore(sdk): update sdk to 8.2.1

- src/popup/locales/cn.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/popup/router/pages/Intro.vue
> Fix onboarding typo

- package-lock.json
- package.json
- src/popup/router/components/Modals/QrCodeReader.vue
> Fix iOS background color after QR scan

- src/popup/router/pages/Account.vue
|before|after|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/133031658-ff47abe5-a5f5-4b1b-9728-b344da24e36e.png)|![image](https://user-images.githubusercontent.com/9008074/133031636-363822fa-57d0-4797-93f6-3dc1d5c49f8d.png)|
> refactor(recent-transactions): do not hide line on transaction list overlap

- package-lock.json
- package.json
- src/popup/locales/en.json
- src/popup/router/components/InputField.vue
- src/popup/router/pages/TransferSend.vue
- src/popup/utils/helper.js
- src/store/index.js
- src/store/plugins/veeValidate.js
- tests/e2e/integration/withdraw.js
- tests/e2e/support/commands.js
This PR is implementing base for refactoring of #1121 with including of vee-validate and example of using in send screen.
> Add validation support for inputs

- .circleci/config.yml
Sample and temporal circleci config to avoid PR checks.
> ci(circleci-build): initial circleci config to avoid failed PR checks

- src/popup/router/pages/Names/Claim.vue
- src/popup/utils/helper.js
It now allows any language\digits
> fix(helper): fix aens check

- src/popup/locales/en.json
- src/popup/router/pages/Names/Claim.vue
- src/store/plugins/veeValidate.js
> feat(claim): check unregistered name

- src/popup/router/pages/TransferSend.vue
> fix(transfer-send): use proper state for active account index

- src/store/actions.js
was fixed in https://github.com/aeternity/ae_mdw/pull/292
closes #1053
> Drop workaround for the duplicate transactions from mdw

- src/lib/wallet.js
- src/popup/router/components/TransactionList.vue
- src/popup/router/components/TransactionOverview.vue
> Fix displaying transaction to a name

- src/popup/router/components/FungibleTokens/DetailsRow.vue
- src/popup/router/components/Loader.vue
- src/popup/router/components/Textarea.vue
- src/popup/router/pages/Address.vue
- src/popup/router/pages/CommentNew.vue
- src/popup/router/pages/Intro.vue
- src/popup/router/pages/Networks.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/SecuritySettings.vue
- src/popup/router/pages/SignMessage.vue
- src/popup/router/pages/SuccessTip.vue
- src/popup/router/pages/TermsOfService.vue
- src/popup/router/pages/TipsClaim.vue
- src/popup/router/pages/TipsSend.vue
- src/popup/router/pages/TransferSend.vue
- src/styles/global.scss
- tests/unit/__snapshots__/snapshot.spec.js.snap
The rest classes in the `global.scss` are used in several pages, which need to be rebranded. After this pages would be rebranded the `global.scss` would be fully cleaned.
> Clean up global styles

- src/popup/router/components/Truncate.vue
fixes #1247,
also fixing scroll issue when preffered/default name changed
> Fix truncate scrolling on string change

- src/popup/router/components/AccountInfo.vue
- src/popup/router/components/AccountSwitcher.vue
> Fix small account card style issues

- package-lock.json
- package.json
- src/popup/App.vue
- src/popup/locales/en.json
- src/popup/router/components/NodeConnectionStatus.vue
- src/store/mutations.js
> feat(status): add offline status

- src/popup/router/components/AccountInfo.vue
- src/popup/router/components/AuctionCard.vue
- src/popup/router/components/Header.vue
- src/popup/router/components/NameItem.vue
- src/popup/router/components/NodeConnectionStatus.vue
- src/popup/router/components/NotificationItem.vue
- src/popup/router/components/Overview.vue
- src/popup/router/components/TokenAmount.vue
- src/popup/router/pages/Account.vue
- src/popup/router/pages/TransactionDetails.vue
part of #1049 (or even fixes the whole issue what do you think @etharner?)
> Utilize line-height in rebranded pages

- package-lock.json
- package.json
- src/popup/router/components/TransactionList.vue
- src/popup/router/index.js
- src/popup/router/pages/Account.vue
- src/popup/router/pages/TransactionDetails.vue
- src/popup/utils/index.js
- src/store/actions.js
- src/store/getters.js
- src/store/index.js
- src/store/migrations/05-change-transactions-structure.js
- src/store/migrations/index.js
- src/store/mutations.js
- src/store/utils.js
fixes #944,
fixes #1234
- also fixing issue with TransactionDetails page
- Stop storing transactions in the localStorage (it was like that despite the fact that stored transactions was not used to show them)
> Refactor transaction fetching

- src/popup/locales/en.json
- src/popup/router/pages/SignTransaction.vue
- src/popup/router/routes/index.js
- tests/pages/index.html
original PR #930 I've force pushed it, and now can not reopen it.
> Sign transaction through deeplink

- src/store/actions.js
> fix(actions): set time correctly for the TipWithdrawn transactions

- CHANGELOG.md
- config.xml
- package-lock.json
- package.json
@Liubov-crypto please check this pr
> chore(release): 0.9.8

- src/popup/utils/helper.js
- tests/e2e/integration/account.js
- tests/unit/__snapshots__/snapshot.spec.js.snap
- tests/unit/account-card.spec.js
- tests/unit/account-switcher.spec.js
- tests/unit/button-plain.spec.js
- tests/unit/checkbox.spec.js
- tests/unit/copy-button.spec.js
- tests/unit/helper-functions/ae-aettos-exchange.spec.js
- tests/unit/helper-functions/categorize-contract-call-tx-object.spec.js
- tests/unit/helper-functions/check-aens-name.spec.js
- tests/unit/helper-functions/check-hash-type.spec.js
- tests/unit/helper-functions/convert-token.spec.js
- tests/unit/helper-functions/to-url.spec.js
- tests/unit/import-account.spec.js
- tests/unit/input-amount.spec.js
- tests/unit/input-field.spec.js
- tests/unit/input-range.spec.js
- tests/unit/link-button.spec.js
- tests/unit/modal.spec.js
- tests/unit/small-modal.spec.js
- tests/unit/snapshot.spec.js
- tests/unit/terms-of-service.spec.js
- tests/unit/textarea.spec.js
> test: improve unit testing coverage

- src/popup/utils/constants.js
- src/popup/utils/transactionTokenInfoResolvers.js
- src/store/getters.js
based on 
- https://github.com/aeternity/mdw-frontend/blob/master/store/utils/transaction-token-info-resolvers.js
links to the contacts:
- https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/WAE.aes
- https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/router/AedexV2Router.aes
link to the list of contracts:
- https://github.com/aeternity/dex-ui/issues/361
> Add dex contracts and resolvers

- src/popup/router/components/FungibleTokens/TokensList.vue
> fix(token-list): set a proper simplex url

- src/popup/router/pages/TransactionDetails.vue
- src/popup/utils/helper.js
- src/store/actions.js
- src/store/plugins/fungibleTokens.js
> perf: do not have a separate request for each fungible token transaction

- src/popup/router/components/FungibleTokens/TokensList.vue
- src/popup/router/components/FungibleTokens/TokensListItem.vue
- src/popup/router/components/InputAmount.vue
- src/popup/router/components/SwapRoute.vue
- src/popup/router/components/Tokens.vue
- src/popup/router/pages/FungibleTokens/TokenDetails.vue
- src/popup/router/pages/Retip.vue
- src/popup/router/pages/TipsSend.vue
- src/popup/router/pages/TransferSend.vue
- src/store/plugins/fungibleTokens.js
This will help us to avoid problems in future.
The contact notation was introduce with a `fungibleTokens` module. It is differs from how other aeternity projects name contact address.
> chore: align every contract id notations

- src/background/wallet.js
- src/lib/wallet.js
> fix: do not reload not connected tabs

- src/popup/router/components/Modals/ConfirmTransactionSign.vue
- src/popup/router/pages/TransactionDetails.vue
> fix(transaction-details): remove fiat amount for tokens other than ae

- src/popup/router/components/Modals/AccountImport.vue
- src/popup/utils/helper.js
- src/store/getters.js
- src/store/modules/accounts/hdWallet.js
fixes https://github.com/aeternity/superhero-wallet/issues/1071
> [SW-202] Subaccounts discovery

- src/popup/router/components/Header.vue
reverting 2947e3f3f565860c9a983bfee94314a32c5a4e66
> Fix back button logic

- src/popup/router/components/TransactionList.vue
- src/popup/router/pages/Dashboard.vue
Wasn't not removing transactions on account change.
> Fix transactions logic

- src/popup/router/components/BoxButton.vue
- src/popup/router/components/Header.vue
> [SW-222] Disable diamond in header & add disabled state for send button

- src/popup/router/components/AddressFormatted.vue
- src/popup/router/components/Modals/TransferReceive.vue
Easier scanning of complex QR codes
> [SW-223] Bigger QR code

- src/popup/router/components/AccountSwitcher.vue
Will not remove the whole logic behind it for two reasons:
- this might break in weird places,
- @paolomolo said that we want to return it soon
> [SW-234, SW-237] Fix account switcher

- src/popup/components/InputField.vue
- src/popup/pages/PermissionsDetails.vue
> [SW-200] Ability to enter letters in the number field

- src/popup/App.vue
- src/popup/components/Modal.vue
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/Modals/QrCodeReader.vue
- src/popup/pages/AccountDetails.vue
- src/popup/pages/Index.vue
- src/popup/pages/TipsClaim.vue
- src/popup/router/index.js
- src/popup/router/web-iframe-popups.js
- src/store/plugins/modals.js
- src/styles/variables.scss
Mostly related to the chrome extension.
> [SW-275] Fix app and modal rounded corners

- src/popup/components/TransactionOverview.vue
https://github.com/aeternity/ae_mdw/blob/fe0e3bec4c7f24da6f2e9fdceabdbb46ea7b0d8e/priv/static/swagger/swagger.json#L2025
> fix(transaction-overiew): show a proper name for transactions to sent to a name

- src/store/plugins/sdk.js
missed in https://github.com/aeternity/superhero-wallet/commit/87ea0f8d6136a970ecbe2f2dc554a02286b3153e#diff-f3804c67e65761e790fe67a25d66f1f6a998e9988e94f6561e53af1fde2890d6
> [SW-379] fix(background): change network/account correctly

- src/popup/pages/SeedPhraseDetailsSettings.vue
https://aeternity-blockchain.atlassian.net/browse/SW-293?focusedCommentId=11781
> [293] seed phrase screen ui

- .github/workflows/main.yml
taken from https://github.com/aeternity/aepp-sdk-js/blob/develop/.github/workflows/main.yml#L20
> build(lint): lint only pull request's commits

- src/popup/locales/en.json
- src/popup/utils/helper.js
fixes #1708.
https://github.com/aeternity/bip39#reminder-for-developers
> fix(account-import): be able to generate account from valid mnemonic

- src/composables/transactionToken.ts
- src/popup/components/TransactionItem.vue
- src/popup/utils/helper.js
- tests/unit/getters/isTxAex9.spec.js
This PR is fixing three different problems:
- two of them were missed in #1706  (one of them was previously fixed in #1658)
- transactions with `AE` token symbol was showed as AE coin
- there were no labels for token `transfer` transaction
- there we no labels for the **pending** `transfer` transactions
> Fix issues related to transaction displaying 

- src/popup/components/AccountInfo.vue
> fix: account card avatar overflow

- src/popup/components/Header.vue
- src/popup/router/routes.ts
fixes small issues missed in https://github.com/aeternity/superhero-wallet/pull/1743
> Fix header related issues

- src/composables/transactionToken.ts
- src/popup/utils/helper.js
- src/store/plugins/veeValidate.js
> [SW-458] URL validation lib causes permission issues

- src/composables/tokensList.ts
- src/popup/pages/AccountDetailsTokens.vue
> [SW-321] improved filter tokens by contract-id

- src/store/plugins/fungibleTokens.js
fixes #1505 
The reason for this change is an issue from middleware https://github.com/aeternity/ae_mdw/issues/1087
> [SW-514] fix(fungible-tokens): load correct token balances info

- src/popup/components/Header.vue
- src/popup/pages/Names/Auction.vue
- src/popup/router/routeNames.ts
- src/popup/router/routes.ts
- tests/e2e/integration/networks.js
also fixes the problem if the user will firstly open a page with a back buton, the back button will return him to a empty browser new tab (introduced in #1743)
> [SW-513, SW-278] Change back button logic

- src/popup/pages/Names/Auction.vue
Remove workaround introduced becasue of https://github.com/aeternity/ae_mdw/issues/509
> [SW-542] refactor: use the correct name structure

- src/store/plugins/names.js
> [SW-559] fix(names): be able to autoExtend names

- src/composables/transaction.ts
- src/popup/components/TransactionInfo.vue
missed in #1763,
missed in #1751
> Fix transaction displaying issues

- src/popup/components/TransactionItem.vue
> fix(transaction-item): add missing icon

- src/popup/components/Modals/ConfirmTransactionSign.vue
> fix(confirm-transaction-sign): show token amount correctly

- src/composables/transactionTokens.ts
- src/composables/transactionTx.ts
- src/popup/components/AccountSwiper.vue
- src/popup/components/LatestTransactionsCard.vue
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/ToggleMultisigButton.vue
- src/popup/components/TransactionInfo.vue
- src/popup/components/TransactionItem.vue
- src/popup/components/TransactionLabel.vue
- src/popup/components/TransactionList.vue
- src/popup/components/TransactionOverview.vue
- src/popup/components/TransactionTagList.vue
- src/popup/pages/MultisigProposalDetails.vue
- src/popup/pages/TransactionDetails.vue
- src/popup/router/routes.ts
- src/popup/utils/utils.ts
- src/store/actions.js
- src/store/getters.js
- src/store/plugins/fungibleTokens.js
- src/types/index.ts
- src/types/router.ts
- tests/unit/transaction-details.spec.js
missed in #1851,
missed in #1794,
missed in #1822,
missed in #1819,
missed in #1764
part of #1809
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/220843567-38ecfb86-08f0-4461-8dfe-4c82ca3bba5d.png)|![image](https://user-images.githubusercontent.com/9008074/220847443-872ea289-38f8-411f-abe1-d4b5eccf8944.png)|
> [SW-638, SW-642, SW-654, SW-655, SW-669, SW-670, SW-674, SW-677, SW-678, SW-681, SW-682] Fix transaction displaying

- src/store/getters.js
> [SW-686] refactor: show transactions sent to yourself as spent

- src/popup/utils/helper.js
- src/popup/utils/utils.ts
> [SW-693] fix: calculate name claim fee correctly

- src/composables/multisigTransactions.ts
- src/composables/topHeader.ts
> Refactor: use topHeader composable data in multisigTransactions

- src/popup/components/Modals/SpendSuccess.vue
- src/popup/components/Modals/TransferSend.vue
> [SW-592] Fix payload fee calculation

- src/background/popupHandler.js
- src/popup/utils/constants.ts
- src/popup/utils/utils.ts
- src/store/modules/accounts/hdWallet.js
> [SW-798] Handle unsupported tx types correctly in the popups

- .github/workflows/main.yml
This PR is supported by the Æternity Crypto Foundation
> ci: run commitlint only on pull_request

- src/composables/modals.ts
- src/popup/pages/Names/Claim.vue
- src/types/index.ts
> [SW-865] Fix name claim

- src/popup/components/TransactionOverview.vue
- src/popup/components/TransactionTagList.vue
- src/popup/utils/testsConfig.ts
- tests/e2e/integration/other.js
- tests/unit/background/popup-handler.spec.js
- tests/unit/getters/get-tx-amount-total.spec.js
- tests/unit/getters/isTxAex9.spec.js
- tests/unit/helper-functions/categorize-contract-call-tx-object.spec.js
- tests/unit/helper-functions/validate-hash.spec.js
- tests/unit/transaction-tag-list.spec.js
part of #1445
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/233638664-2afafcd0-395d-4c11-a30f-2d3c163ee5e4.png)|![image](https://user-images.githubusercontent.com/9008074/233638736-68dd7195-8e03-4fbb-a1fa-fef014da3691.png)|
> Improve test coverage

- jest.config.js
Based on https://github.com/jestjs/jest/issues/4422#issuecomment-770274099
This PR is supported by the Æternity Crypto Foundation
> fixup: update unit tests to run with vue3

- src/store/plugins/sdk.js
missed in https://github.com/aeternity/superhero-wallet/pull/1948
> fix: be able to sign message in iframe

- src/background/index.js
> refactor: remove unused openTipPopup

- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/pages/Popups/Connect.vue
- src/popup/pages/Popups/MessageSign.vue
- src/popup/router/index.ts
fixes #2054,
potential fix of #2056,
also speeds up `aex2-popups` e2e test by 30 percent (~17 seconds)
Improvements
- lastRouteKey logic ~**200**ms
- sdk initialization ~**6000**ms
> [SW-906] Improve popup performance

- src/background/wallet.js
- src/popup/pages/NotFound.vue
- src/popup/router/index.ts
- src/popup/router/routes.ts
> [SW-904] fix(popup): handle no props correctly

- src/popup/components/TransferSendForm.vue
- src/store/plugins/veeValidate.js
- Removed warnings from Transfer Send validation form and made them to display as errors.
> [SW-888] Feature/error filtering issue

- src/popup/App.vue
- src/popup/components/Modal.vue
- src/popup/components/Modals/QrCodeReader.vue
- src/styles/global.scss
see https://v3-migration.vuejs.org/breaking-changes/mount-changes.html
make outer `#app` act in the same way as body & change inner `#app` to `.app-wrapper`
> fix: duplicate app

- src/store/plugins/names.js
Minor fix that was creating issues with chain names and account images
> [SW-940] fix:  initialize chain name on store

- src/composables/transactionAndTokenFilter.ts
- src/popup/components/TransactionAndTokenFilter.vue
Refactor usage of instance.ref so it will update to latest value
> fix: filters and searchbar in transactions

- src/popup/router/routes.ts
> fix: do not save not found page as last route

- src/composables/latestTransactionList.ts
- src/store/actions.js
- src/store/plugins/fungibleTokens.js
> [SW-360] Improve transaction fetching performance

- src/manifest.json
- src/popup/App.vue
- src/styles/global.scss
Changes required to be able to build extension after adding Ionic.
> feat: build extension with ionic

- src/popup/components/TransactionOverview.vue
- src/popup/locales/en.json
- src/popup/pages/FungibleTokens/TokenDetails.vue
- src/popup/pages/MultisigProposalDetails.vue
- src/popup/pages/TransactionDetails.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2136
> fix(transaction-overview): use correct label for a contract call

- src/store/actions.js
> fix: add correct type for tipWithdrawnTransactions

- src/composables/multisigAccountCreate.ts
- src/lib/accounts/superhero.ts
- src/store/modules/accounts/hdWallet.js
- src/store/modules/accounts/index.js
mostly it is a revert of 52af43f669211336cd0f746aa0cfd2d8d0bab771
> [SW-1052, SW-1074] fix: creation of multisig with inactive account

- src/popup/components/TransferSendForm.vue
- tests/e2e/integration/withdraw.js
> [SW-1085] fix(transfer-send-form): handle warnings correctly

- src/composables/maxAmount.ts
> [SW-1086] fix: calculate tip url fee correctly

- src/background/wallet.js
Fixed the broken logic from PR https://github.com/aeternity/superhero-wallet/pull/2185
> Fix logic of sharing wallet info when sdk is not blocked

- package-lock.json
- package.json
- src/background/popupHandler.ts
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/locales/cn.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/store/modules/accounts/hdWallet.js
- src/types/index.ts
labels in `advancedDetails` were missed in #2135, used the same approach as in #2158
> [SW-988] Validate transaction before signing

- src/composables/accounts.ts
- src/composables/aeSdk.ts
- src/composables/multisigAccounts.ts
- src/lib/FramesConnection.ts
- src/popup/components/AccountInfo.vue
- src/popup/components/AccountItem.vue
- src/popup/components/AddressTruncated.vue
- src/popup/components/TransactionOverview.vue
- src/popup/pages/TransactionDetails.vue
- src/protocols/aeternity/libs/AeScan.ts
- src/protocols/aeternity/libs/AeSdkSuperhero.ts
- tests/unit/helper-functions/validate-hash.spec.js
...and fix the typo in the name of the Sdk lib.
> [Multichain] Move AE libs to protocol dir

- src/constants/common.ts
- src/popup/components/Modals/WarningDappBrowser.vue
- src/popup/locales/en.json
- src/popup/pages/AppsBrowser.vue
- src/popup/router/modals.ts
- src/popup/router/routeNames.ts
> [In-App Browser] feat: add warning modal in order to connect in dapp browser

- src/popup/pages/Names/AuctionBid.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2186
> [SW-1116] fix: apply correct validation rules for name bidding

- src/background/store.js
- src/store/modules/invites.js
missed in https://github.com/aeternity/superhero-wallet/pull/2150
> [SW-1123] Fix invite claim

- src/lib/AeScan.ts
- src/popup/components/AddressTruncated.vue
- tests/unit/transaction-details.spec.js
missed in https://github.com/aeternity/superhero-wallet/pull/1815
> [SW-1124] Fix contract explorer links

- src/popup/components/TransferSendForm.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2190
> [SW-1128] fix: use the correct warnings condition

- src/store/modules/accounts/hdWallet.js
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit
> refactor: adjust account discovery logic

- src/popup/components/IconWrapper.vue
This fixes following visual issue:
> Hotfix: Icon sizes in dashboard cards

- src/popup/locales/cn.json
- src/popup/locales/de.json
- src/popup/locales/en.json
- src/popup/locales/fr.json
- src/popup/locales/it.json
- src/popup/locales/ru.json
> [SW-1188] feat: adjust connect modal wording

- src/composables/accounts.ts
- src/composables/pendingMultisigTransaction.ts
- src/popup/components/AccountCardAdd.vue
- src/popup/components/AccountDetailsBase.vue
- src/popup/components/AccountInfo.vue
- src/popup/components/Modals/MultisigVaultCreate.vue
- src/popup/components/MultisigProposalConsensus.vue
- src/popup/components/MultisigVaultCreateReview.vue
- src/popup/components/NetworkRow.vue
- src/popup/locales/en.json
- src/popup/pages/AccountDetailsMultisig.vue
- src/popup/pages/CommentNew.vue
- src/popup/pages/Dashboard.vue
- src/protocols/aeternity/components/TransferReviewTip.vue
- src/protocols/aeternity/components/TransferSendForm.vue
- src/store/getters.js
- src/store/modules/accounts/hdWallet.js
- src/store/modules/accounts/index.js
- src/store/plugins/fungibleTokens.js
- src/store/plugins/names.js
- src/store/utils.js
- src/types/index.ts
- src/utils/common.ts
> [SW-1148, SW-1149, SW-1158, SW-1181, SW-1164] Fix account swiping & add protocol to default account name

- src/popup/components/AccountCardMultisig.vue
- src/popup/components/AccountInfo.vue
- src/popup/components/AccountItem.vue
- src/popup/components/AccountSelectOptionsItem.vue
- src/popup/components/AccountSelector.vue
- src/popup/components/AddressTruncated.vue
- src/popup/components/NotificationItem.vue
- src/popup/pages/AccountDetailsMultisig.vue
- src/popup/pages/TipsClaim.vue
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/bitcoin/composables/btcNetworkSettings.ts
- src/protocols/bitcoin/config.ts
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/bitcoin/libs/Blockstream.ts
- src/protocols/bitcoin/views/TransactionDetails.vue
> [SW-1022] Decide Explorer for Bitcoin & Dogecoin

- src/popup/components/TransactionLabel.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2158
> [SW-1133] fix(transaction-label): show contract related labels

- package-lock.json
- package.json
- src/composables/middleware.ts
> [SW-1218] refactor: adjust middleware swagger file fetching

- src/popup/components/Modals/MultisigProposalConfirmActions.vue
- src/popup/components/UrlStatus.vue
https://vue-i18n.intlify.dev/api/composition.html#tm-key
> [SW-1242] fix: show the text correctly

- src/composables/transactionTx.ts
missed in https://github.com/aeternity/superhero-wallet/pull/2158
> [SW-1245] fix: show correct label for claim transaction

- src/popup/pages/About.vue
- tests/unit/snapshot.spec.js
> [SW-1213] fix(about): show correct node status

- src/popup/components/TransactionList.vue
- src/popup/pages/FungibleTokens/TokenTransactions.vue
- src/protocols/aeternity/views/AccountDetailsTransactions.vue
missed in https://github.com/aeternity/superhero-wallet/pull/1970
> [SW-1252] fix: load filtered transactions correctly

- .github/workflows/main.yml
Added at main.yml GitHub Wokflow steps to produce new APK at each branch's push.
> chore: add android build functionality

- src/composables/deepLinkApi.ts
- src/composables/transferSendForm.ts
- src/lib/RouteQueryActionsController.ts
- src/popup/components/ProtocolSpecificView.vue
- src/popup/components/TransferSend/TransferSendRecipient.vue
- src/popup/pages/Dashboard.vue
- src/popup/router/index.ts
- src/protocols/aeternity/components/TransferSendForm.vue
- src/utils/common.ts
> [SW-1206] Don't open the transfer send modal when accessing the page from deep links

- src/composables/transactionList.ts
> fix(transaction-list): correct aex9 event condition

- src/popup/components/Modals/ClaimSuccess.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2319
> fix: show ClaimSuccess modal correctly

- src/popup/components/Modals/ConfirmRawSign.vue
- src/popup/pages/SignTransaction.vue
missed in https://github.com/aeternity/superhero-wallet/pull/2139
> Fix ability to broadcast signed via deeplink transaction

- src/popup/components/Modals/TransferSendBase.vue
> [SW-1351] fix: buttons on multisig propose

- package-lock.json
- package.json
- src/composables/maxAmount.ts
- src/popup/pages/Names/AuctionBid.vue
- src/popup/pages/Names/Claim.vue
> build: update sdk to 13.2.2

- src/composables/ui.ts
- src/popup/App.vue
- src/popup/components/Modals/AccountCreate.vue
- src/popup/components/TransferSend/TransferReviewBase.vue
- src/popup/pages/CommentNew.vue
- src/popup/pages/FungibleTokens/TokenContainer.vue
- src/popup/pages/Invite.vue
- src/popup/pages/MultisigProposalDetails.vue
- src/popup/pages/Names/AuctionBid.vue
- src/popup/pages/Names/Claim.vue
- src/popup/pages/Retip.vue
- src/popup/pages/TipsClaim.vue
- src/protocols/aeternity/views/TransactionDetails.vue
- src/protocols/bitcoin/views/TransactionDetails.vue
- tests/unit/transaction-details.spec.js
Positioning elements with `position:absolute|fixed` in Ionic doesn't work with elements in nested `router-outlets`, like tabs content, because it will use the position of the inner-most `router-outlet`.
This is why the `<Loader/>` component was moved to the `App.vue` and visibilty is controlled through the `useUi` composable
https://ionicframework.com/docs/api/content#fixed-content
> [SW-1359] fix: full screen loading

- src/popup/components/Modals/AssetSelector.vue
- src/popup/components/TransferSend/TransferReviewBase.vue
- src/popup/pages/FungibleTokens/TokenContainer.vue
- src/popup/pages/MultisigProposalDetails.vue
- src/popup/pages/Names/Auction.vue
- src/popup/popup.ts
> [SW-1370, SW-1371] fix: set full screen loader correctly

- src/popup/components/Header.vue
- src/popup/components/Modal.vue
> feat: handle hardware back button

- src/popup/components/ProtocolSpecificView.vue
- src/popup/pages/AccountDetailsMultisigTransactions.vue
- src/popup/pages/MultisigDetails.vue
- src/popup/pages/Names/NamesList.vue
- src/protocols/aeternity/views/AccountDetailsTokens.vue
- src/protocols/aeternity/views/AccountDetailsTransactions.vue
- src/protocols/bitcoin/views/AccountDetailsTransactions.vue
- src/types/index.ts
> fix: ionic lifecycle methods do not trigger

- src/protocols/aeternity/views/AccountDetailsTransactions.vue
- src/protocols/bitcoin/views/AccountDetailsTransactions.vue
> fix: account details doesnt always cover whole area

- src/popup/App.vue
- src/popup/popup.ts
> fix: fix refresh action in daepps browser. Issue arised on ios.

- src/composables/multisigTransactions.ts
> fix: sort pending multisig transaction correctly

- src/popup/App.vue
- src/popup/animations/popIn.ts
- src/popup/animations/popOut.ts
- src/popup/components/Header.vue
closes #2465 
Also improved page transitions for account-details & added blur effect requested by @onvisions
> fix: network switcher visible during page transitions

- src/lib/RouteLastUsedRoutes.ts
> fix: router next function is called twice

- src/composables/multisigAccounts.ts
- src/popup/App.vue
- src/popup/components/ToggleMultisigButton.vue
> fix: redirect if no multisig

- src/composables/latestTransactionList.ts
- src/composables/transactionList.ts
- src/popup/components/AccountDetailsTransactionsBase.vue
- src/popup/components/TransactionList.vue
- src/popup/pages/AccountDetailsMultisigTransactions.vue
- src/popup/pages/Dashboard.vue
- src/popup/pages/FungibleTokens/TokenTransactions.vue
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/composables/aeNames.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/aeternity/views/AccountDetailsTransactions.vue
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/bitcoin/views/AccountDetailsTransactions.vue
- src/types/index.ts
- tests/e2e/integration/other.js
- tests/e2e/support/commands.js
> [SW-1199, SW-1204] Latest Tx widget - problem with btc transaction

- package-lock.json
- package.json
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/101,
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/102,
> build: run npm update

- package-lock.json
- package.json
- src/composables/accounts.ts
- src/icons/coin/ethereum.svg
- src/popup/components/Modals/ClaimGiftCard.vue
- src/popup/components/Modals/TransferReceiveBase.vue
- src/popup/components/ProtocolIcon.vue
- src/popup/components/TransactionSpeedPicker.vue
- src/popup/components/buttons/BtnMaxAmount.vue
- src/popup/locales/en.json
- src/protocols/aeternity/components/TransferSendForm.vue
- src/protocols/bitcoin/components/TransferSendForm.vue
- src/protocols/ethereum/components/TransferReview.vue
- src/protocols/ethereum/components/TransferSendForm.vue
- src/protocols/ethereum/composables/ethBaseFee.ts
- src/protocols/ethereum/composables/ethNetworkSettings.ts
- src/protocols/ethereum/config.ts
- src/protocols/ethereum/helpers/index.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/protocols/ethereum/views/TransferReceiveModal.vue
- src/protocols/ethereum/views/TransferSendModal.vue
- src/protocols/ethereum/views/index.ts
- src/store/plugins/veeValidate.js
- src/types/index.ts
_fee calculation:_ 
- great article on how to calculate fee, [see](https://www.blocknative.com/blog/eip-1559-fees)
- ethereum docs on calculating fees, [see](https://ethereum.org/en/developers/docs/gas/#block-size)
- `Base Fee` is 100% automatic and readable directly from the network.
- Right now we are setting `Max Priority Fee` hardcoded for all settings (slow, medium, fast) as `Max Priority Fee` is normaly set by the user, so I believe we could also have a `custom fee` field where the user can set his own `Max Priority Fee` for slower or faster transactions
- **`Fee` =  `Base Fee` + `Max Priority Fee`**
- **`Max Fee` = (2 * `Base Fee`) + `Max Priority Fee`**
> Ethereum transfer receive & send views

- src/popup/components/TransactionTagList.vue
> fix: show a correct tag for a pending multisig proposal

- .eslintrc.js
- src/composables/copy.ts
- src/composables/maxAmount.ts
- src/composables/permissions.ts
- src/composables/tokensList.ts
- src/composables/transactionTokens.ts
- src/composables/viewport.ts
- src/popup/animations/fade.ts
- src/popup/animations/popIn.ts
- src/popup/animations/popOut.ts
- src/popup/components/MainBalance.vue
- src/popup/components/MultisigProposalConsensus.vue
- src/popup/components/TransactionOverview.vue
- src/popup/components/UrlStatus.vue
- src/popup/pages/Retip.vue
- src/protocols/aeternity/helpers/transactionTokenInfoResolvers.ts
- src/protocols/aeternity/views/TransferSendModal.vue
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/bitcoin/views/TransferSendModal.vue
- src/types/filter.ts
- src/types/index.ts
Semicolons required for the line ending in the TS interfaces.
> Refactor: Enforce consistent interface member delimiter style

- src/popup/pages/Names/AuctionHistory.vue
> fix: show a proper address of a bidder

- src/protocols/ethereum/config.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/protocols/ethereum/libs/Etherscan.ts
> feat: eth add explorer urls

- src/popup/components/TransactionListItem.vue
- src/popup/pages/AccountDetailsMultisigTransactions.vue
> fix: show pending multisig transaction correctly

- src/popup/components/TransferSend/TransferSendRecipient.vue
- src/protocols/aeternity/composables/aeTippingUrls.ts
> fix: fetch error when opening eth send

- src/protocols/ethereum/config.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
Add default values when adding new network to match aeternity implementation
> feat: eth add default network values

- src/popup/pages/SignTransaction.vue
> fix: be able to sign transaction via deeplink

- src/popup/components/Modals/ConfirmTransactionSign.vue
> refactor: show decoded payload on transaction signing

- src/popup/components/AddressTruncated.vue
- src/popup/pages/FungibleTokens/TokenContainer.vue
fixes #2565,
missed in https://github.com/superhero-com/superhero-wallet/pull/2237
> fix: correct contactId explorer link

- src/composables/aeSdk.ts
> fix: do not use sdk without node

- src/protocols/ethereum/libs/EthereumAdapter.ts
Do not wait for response when sending transaction
Instead calculate hash beforehand
> feat: eth dont wait for tx confirmation when sending

- src/composables/fungibleTokens.ts
- src/protocols/ethereum/components/TransferReview.vue
> fix: correctly fix eth api limit issue

- src/protocols/ethereum/components/TransferSendForm.vue
> fix(ethereum): validate token amount when asset is predefined

- public/index.html
> fix: index.html points to missing favicon files

- src/composables/aeSdk.ts
> fix: get correct dryAeSdk after changing network

- src/composables/transactionTokens.ts
- src/popup/components/TransactionTokenRows.vue
- src/protocols/bitcoin/views/TransactionDetails.vue
- src/protocols/ethereum/views/TransactionDetails.vue
> fix: show correct icons & amount on tx details

- src/protocols/aeternity/helpers/index.ts
> fix: missing payload from multisig tx

- src/popup/components/TransactionList.vue
closes #2630 
I wonder why it wasn't working 😅
> fix: search transactions by contract

- public/index.html
This code/font is deprecated, no longer used in our application.
> perf: remove request for unused Inter fonts

- src/popup/pages/Names/Auction.vue
Originally was made here https://github.com/superhero-com/superhero-wallet/pull/1759, but i think it was lost due to rebasing process.
https://github.com/aeternity/ae_mdw/issues/509
> refactor: use the correct auction structure

- src/composables/fungibleTokens.ts
- src/popup/components/TransactionTagList.vue
- src/protocols/aeternity/helpers/index.ts
- src/protocols/aeternity/views/TransactionDetails.vue
> fix: tip-in transaction details

- android/app/build.gradle
- android/app/src/main/res/values/styles.xml
> fix: splash screen bg color on android

- public/index.html
> feat: add meta description

- src/popup/pages/Names/Auction.vue
- src/types/index.ts
> fix: show auction bids

- src/popup/router/routes.ts
closes #2543 
The error does not cause any issues, so maybe it is preferable to leave it as is than to add these checks
> fix: missing required param error

- src/popup/locales/en.json
- src/popup/pages/SeedPhraseVerifySettings.vue
> feat: seed-phrase verification should not redirect

- src/protocols/aeternity/config.ts
> chore: change backend urls

- src/popup/components/AccountCardAdd.vue
- src/popup/components/AccountDetailsBase.vue
- src/popup/components/AccountSwiperSlide.vue
- src/popup/components/BulletSwitcher.vue
- src/popup/components/InviteItem.vue
- src/popup/components/Modals/MultisigVaultCreate.vue
- src/popup/components/TransactionListItem.vue
- src/popup/components/TransferSend/TransferReviewBase.vue
- src/popup/pages/Invite.vue
- src/popup/pages/PrivacyPolicy.vue
- src/popup/pages/TermsOfService.vue
- tests/unit/__snapshots__/snapshot.spec.js.snap
This PR adds missing data-cy ids requested by @dvdbak
> chore: add missing data-cy ids

- src/popup/components/TransactionListItem.vue
> fix: check for null microTime

- src/composables/transactionList.ts
- src/protocols/aeternity/views/TransactionDetails.vue
part of #2675,
missed in https://github.com/superhero-com/superhero-wallet/commit/39d94200d0c0688406f843b5d9ec9b8fd69a074d,
> fix(aeternity): show correct transaction details for token transfers

- src/composables/deepLinkApi.ts
- src/popup/pages/Address.vue
- src/popup/pages/InviteClaim.vue
- src/popup/pages/SignMessage.vue
- src/popup/pages/SignTransaction.vue
- src/popup/router/index.ts
> Fix deeplinks on mobile

- src/composables/transactionTokens.ts
> fix(transaction-list): show allow transaction correctly

- src/popup/pages/SignMessage.vue
> feat: support signing messages encoded as hex

- src/composables/notifications.ts
> fix: show wallet notifications

- src/popup/pages/NetworkForm.vue
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
> fix: do not allow to add invalid custom node

- src/popup/components/TransactionOverview.vue
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/views/TransactionDetails.vue
- src/protocols/ethereum/helpers/index.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/protocols/ethereum/libs/EtherscanService.ts
- src/protocols/ethereum/libs/EthplorerService.ts
- src/protocols/ethereum/views/TransactionDetails.vue
> fix: show correct erc-20 transaction details

- src/composables/fungibleTokens.ts
- src/composables/latestTransactionList.ts
> fix: ensure that available tokens are correct for the network

- src/popup/pages/AccountDetailsMultisig.vue
> fix: multisig transaction list is displaying partly

- commitlint.config.js
> refactor: config commitlint more precisely

- src/popup/components/NetworkRow.vue
- src/popup/components/RadioButton.vue
> fix: switch networks correctly

- src/popup/components/LinkButton.vue
- src/popup/components/TransactionDetailsBase.vue
- src/popup/locales/en.json
- src/popup/pages/Assets/AssetDetails.vue
- src/popup/pages/Assets/AssetDetailsInfo.vue
closes #2574 
also fixes issue no. 1 from https://github.com/superhero-com/superhero-wallet/pull/2736#issuecomment-1959775501
> feat: update asset details page

- src/popup/pages/Assets/AssetDetails.vue
> fix: remove swap button from non ae assets

- src/popup/components/ProtocolSpecificView.vue
- src/protocols/aeternity/views/AccountDetails.vue
- src/protocols/aeternity/views/AccountDetailsTokens.vue
- src/protocols/bitcoin/views/AccountDetails.vue
- src/protocols/ethereum/views/AccountDetails.vue
- src/protocols/ethereum/views/AccountDetailsTokens.vue
- src/types/index.ts
missed in #2618  as it was done on develop branch
> fix: eth transaction list displaying partly

- src/composables/accountAssetsList.ts
- src/popup/components/TransactionTagList.vue
- src/popup/pages/Assets/AssetDetails.vue
fixes issues from eth-support branch
> 4. /multisig/coins/aeternity/details page is broken:
> 
> ![coin det ](https://private-user-images.githubusercontent.com/69896204/307008652-c3dbd237-96a3-41b6-bd86-129d47da7e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjczOTMsIm5iZiI6MTcwODY2NzA5MywicGF0aCI6Ii82OTg5NjIwNC8zMDcwMDg2NTItYzNkYmQyMzctOTZhMy00MWI2LWJkODYtMTI5ZDQ3ZGE3ZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA1NDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OGYyN2U1YjE3MDgzZGM4MzVkMmRiOGQyYWI5ZjAwNzY2YWI1ZDJiNTE3NzlmODFhYmVmNzk3ZDk …
> Fix several multisig issues

- src/popup/pages/Assets/AssetDetails.vue
missed in #2742, because of #2744
> fix(multisig): show correct fiat value for assets

- .github/workflows/main.yml
- .github/workflows/test.yml
The goal of this PR is to test and build PRs faster.
> ci: split test and build workflows

- src/popup/components/DashboardHeaderMultisig.vue
- src/popup/pages/MultisigProposalDetails.vue
fixes:
```
logger.ts:50 Invalid prop: type check failed for prop "totalBalance".
Expected String with value "0.01", got Number with value 0.01. at <TotalWalletAmount>
Invalid prop: type check failed for prop "to".
Expected String with value "undefined", got Undefined  at <LinkButton>
```
> Fix multisig props validation

- src/popup/components/BackToTop.vue
- src/popup/components/Modals/AssetSelector.vue
- src/styles/variables.scss
> fix: back-to-top inside asset selector

- src/popup/components/NameItem.vue
- src/protocols/aeternity/composables/aeNames.ts
> fix: show correct default name for the selected network

- vue.config.js
Removes warning about unset vue feature flag
> chore: remove vue feature flag warning

- src/protocols/ethereum/libs/EthplorerService.ts
https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API#freekey-limits
> refactor(ethereum): avoid showing wrong token info

- src/composables/aeSdk.ts
- src/composables/permissions.ts
- src/offscreen/utils.ts
- src/protocols/aeternity/libs/AeAccountHdWallet.ts
- src/utils/common.ts
> fix: show sign confirmation modals

- src/popup/components/AccountDetailsBase.vue
- src/popup/components/TransactionAndTokenFilter.vue
> fix: do not show previous page filters

- src/lib/ProtocolAdapterFactory.ts
- src/popup/components/AddressFormatted.vue
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
> fix(aeternity): format recipient address correctly

- src/composables/latestTransactionList.ts
- src/composables/transactionList.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
> fix(aeternity): show pending and tip withdrawn transactions

- src/popup/components/AccountCardTotalTokens.vue
- src/popup/locales/cn.json
- src/popup/locales/en.json
- src/popup/locales/es.json
This PR applies the rules of pluralization for tokens wording.
> refactor: update fungible token wording

- src/composables/transactionList.ts
> fix: cache loaded transactions if state did not change

- src/composables/fungibleTokens.ts
- src/protocols/ethereum/libs/EthplorerService.ts
- src/types/index.ts
> feat: extract custom tokens from token balances

- src/popup/components/form/FormTextarea.vue
> refactor: show recipient field required message

- src/popup/components/TransactionList.vue
> fix: load old transactions

- src/composables/fungibleTokens.ts
> fix: reset token lists on network change

- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/ethereum/composables/ethMaxAmount.ts
- src/protocols/ethereum/libs/EthplorerService.ts
- src/types/index.ts
> fix: converted balance should not be 0 for small amounts

- src/popup/components/DashboardWrapper.vue
- src/popup/pages/Dashboard.vue
- src/popup/pages/DashboardMultisig.vue
> fix: viewport element missing in dashboard

- src/composables/multisigTransactions.ts
- src/popup/components/Modals/MultisigProposalConfirmActions.vue
- src/popup/pages/MultisigProposalDetails.vue
> refactor: do not change active account to sign multisig action

- src/composables/pendingMultisigTransaction.ts
> fix(multisig): update pending transaction info correctly

- src/composables/accountAssetsList.ts
- src/popup/components/PendingMultisigTransactionCard.vue
- src/popup/pages/AccountDetailsMultisigTransactions.vue
- src/popup/pages/Assets/AssetDetails.vue
- src/popup/pages/Assets/AssetDetailsInfo.vue
- src/popup/pages/MultisigProposalDetails.vue
> fix: missing coin details in assetDetails page

- src/protocols/ethereum/views/TransactionDetails.vue
> fix(ethereum): show pending transaction details correctly

- src/protocols/aeternity/libs/AeternityAdapter.ts
missed in https://github.com/superhero-com/superhero-wallet/pull/2659
> fix(aeternity): aex9 unfinished transaction info

- src/popup/components/DashboardBase.vue
- src/popup/pages/DashboardMultisig.vue
missed in https://github.com/superhero-com/superhero-wallet/pull/2307
> fix(multisig): show total correctly

- src/popup/components/TokenAmount.vue
- src/popup/pages/PermissionManager.vue
fixes #2880 
|develop|fix|
|---|---|
|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/f52f3a50-1287-4fb5-bbb4-a98fb03416ca)|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/37bd3b74-4308-4921-86ae-2e3f91a5555f)|
> fix(token-amount): justify content correctly

- package-lock.json
- package.json
- src/protocols/ethereum/components/TransferSendForm.vue
- src/protocols/ethereum/composables/ethFeeCalculation.ts
> refactor: eth fee calculation

- src/popup/components/Avatar.vue
fixes #2912,
missed in https://github.com/superhero-com/superhero-wallet/pull/2873
> fix: show correct avatar for names

- src/popup/components/CardMnemonic.vue
- src/popup/components/SeedPhraseBadge.vue
- src/popup/components/SeedPhraseNotification.vue
- src/popup/pages/SeedPhraseDetailsSettings.vue
- src/popup/pages/SeedPhraseVerifySettings.vue
I have replaced JS notification box position calculations with regular CSS approach: `position: relative;` on parent + `position: absolute; inset: 0;` on notification box.
> fix: seed phrase notification position

- src/protocols/aeternity/libs/AeternityAdapter.ts
> fix(aeternity): show all asset related transactions

- src/migrations/008-mnemonic-cordova-to-ionic.ts
- src/popup/pages/Index.vue
> fix(ios): discover accounts for new wallet correctly

- src/composables/fungibleTokens.ts
> fix: load available tokens when adding an account on a new blockchain

- src/composables/transactionList.ts
- src/protocols/ethereum/libs/EtherscanService.ts
- src/protocols/ethereum/libs/EthplorerService.ts
> fix: eth tx list not loading

- src/popup/components/AccountInfo.vue
- src/popup/components/Avatar.vue
- src/popup/components/NameItem.vue
- src/popup/pages/Names/NamesList.vue
- src/types/index.ts
...and restructure NameItem component.
> fix: prevent cutting off parts of account name letters

- src/protocols/ethereum/config.ts
Endpoints have been updated 
_see https://ethereum-sepolia.publicnode.com/?sepolia_
> chore: update eth node urls

- src/manifest.json
> build: remove unused extension permissions

- package-lock.json
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/110,
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/111
> Fix critical dependency vulnerabilities

- src/lib/initPolyfills.js
- src/migrations/migrationHelpers.ts
- src/popup/components/Modals/ResetWalletModal.vue
> fix: be able to migrate mnemonic from vuex

- src/composables/transactionData.ts
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/protocols/aeternity/views/TransactionDetails.vue
fixes https://github.com/superhero-com/superhero-wallet/issues/2941
> fix: show dex related info only for dex transactions

- src/popup/components/InputAmount.vue
- src/popup/components/InputField.vue
- src/popup/components/TokenAmount.vue
- src/popup/components/TransferSend/TransferSendAmount.vue
- src/popup/components/TransferSendFormBase.vue
- src/popup/locales/en.json
- src/protocols/aeternity/components/TransferSendForm.vue
- src/protocols/ethereum/components/TransferSendForm.vue
- src/styles/global.scss
> fix: eth max button should stay on

- src/composables/maxAmount.ts
fixes #2972,
https://github.com/aeternity/aepp-sdk-js/commit/08d14c2d50c480ccc25f2dc67b0a09d1487c35bb
> fix(aeternity): be able to send max amount

- src/composables/pendingMultisigTransaction.ts
- src/popup/components/TransactionTagList.vue
> fix(multisig): do not fail if no function provided

- src/popup/pages/Index.vue
> feat: show loader on account discovering after migration

- src/constants/stubs.ts
- src/popup/components/InviteItem.vue
- src/popup/components/Modals/ClaimGiftCard.vue
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/Modals/ConfirmUnsafeSign.vue
- src/popup/components/Modals/Default.vue
- src/popup/components/Modals/TransferReceiveBase.vue
- src/popup/components/OpenTransferReceiveModalButton.vue
- tests/e2e/integration/aex2-popups.cy.js
- tests/e2e/integration/deeplinks.cy.js
- tests/e2e/integration/invites.cy.js
- tests/e2e/integration/other.cy.js
- tests/e2e/integration/receive.cy.js
- tests/e2e/integration/transfer-send.cy.js
- tests/e2e/support/commands.js
- tests/pages/index.html
- tests/unit/composables/open-scan-qr-modal.spec.js
- tests/unit/transaction-tag-list.spec.js
fixes https://github.com/superhero-com/superhero-wallet/issues/2204,
par of #1445
> Improve e2e and unit test coverage

- src/popup/components/AccountSwiper.vue
- src/popup/pages/DashboardMultisig.vue
> fix(multisig): slide to active account

- src/composables/fungibleTokens.ts
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/components/TransferReview.vue
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/ethereum/components/TransferReview.vue
- src/protocols/ethereum/components/TransferSendForm.vue
- src/protocols/ethereum/composables/ethFeeCalculation.ts
- src/protocols/ethereum/helpers/index.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/types/index.ts
> fix: estimate gas limit for erc20 transfers

- src/popup/components/Modals/TransferReceiveBase.vue
> fix: multisig transfer receive share correct address

- CHANGELOG.md
- android/app/build.gradle
- ios/App/App.xcodeproj/project.pbxproj
- package-lock.json
- package.json
- src/composables/multisigTransactions.ts
related PR https://github.com/aeternity/ga-multisig-backend/pull/17
> fix: calculate auth tx hash in Ceres

- src/protocols/ethereum/views/TransactionDetails.vue
> fix(ethereum): show token transfer info correctly

- src/composables/invites.ts
> perf: do not create new sdk instance on invite claim

- src/composables/maxAmount.ts
> fix(aeternity): show correct fee in initialization of `TransferSend` modal

- src/composables/aeSdk.ts
- src/composables/permissions.ts
- src/protocols/aeternity/libs/AeAccountHdWallet.ts
I've tested it using https://docs.aeternity.com/aepp-sdk-js/v13.2.2/examples/browser/aepp/
Take over this PR to implement confirmations as you need 🙏 
closes https://github.com/superhero-com/superhero-wallet/issues/2222
> Support payForTx, typed data, delegation signing with a basic confirmation

- src/popup/components/AccountDetailsBase.vue
- src/popup/components/TransactionAndTokenFilter.vue
- src/popup/pages/Assets/AssetDetails.vue
> refactor: hide dex filter on AE asset page

- src/popup/locales/en.json
- src/protocols/bitcoin/components/TransferReview.vue
> Improve dust error

- src/constants/environment.ts
- src/popup/pages/AppsBrowser.vue
closes https://github.com/superhero-com/superhero-wallet/issues/2993
found issues https://github.com/superhero-com/superhero-wallet/pull/3005 https://github.com/aeternity/aepp-sdk-js/issues/1979 https://github.com/superhero-com/superhero-wallet/issues/3007 https://github.com/superhero-com/superhero-wallet/issues/3008
> fix(ios): don't recreate RpcClient on navigation inside page

- src/popup/components/TransactionLabel.vue
- src/popup/components/TransactionOverview.vue
- src/popup/locales/en.json
|develop|fix|
|---|---|
|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/2b721169-0558-4cd9-9628-0f08159ddba7)|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/ecd5b9c3-f347-4a80-afd7-7fed9633f70f)|
|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/a60640e5-2057-4213-8a55-421119de3355)|![image](https://github.com/superhero-com/superhero-wallet/assets/9008074/143700f3-9043-4214-ac0c-308a835385c9)|
> fix: handle pay for tx correctly

- src/popup/components/InputField.vue
- src/popup/pages/AppsBrowser.vue
- src/utils/validators.ts
> Browser's URL input fixes

- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/TransactionDetailsBase.vue
- src/protocols/bitcoin/views/TransactionDetails.vue
- src/protocols/ethereum/views/TransactionDetails.vue
> refactor: show total amount with high precision

- src/popup/locales/de.json
- src/popup/locales/en.json
- src/popup/locales/fr.json
- src/popup/locales/it.json
> fix: adjust wording for failed transaction modal

- src/composables/aeSdk.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
> fix(aeternity): show node connection error

- src/composables/transactionData.ts
- src/popup/components/SwapRoute.vue
- src/protocols/BaseProtocolAdapter.ts
- src/protocols/aeternity/config.ts
- src/protocols/aeternity/helpers/transactionTokenInfoResolvers.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/bitcoin/components/TransferSendForm.vue
- src/protocols/bitcoin/config.ts
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/bitcoin/views/TransactionDetails.vue
- src/protocols/ethereum/components/TransferSendForm.vue
- src/protocols/ethereum/config.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/utils/common.ts
> chore: rename ae coin name to aeternity

- package.json
- src/popup/components/PanelTableItem.vue
- src/popup/pages/About.vue
- tests/unit/__snapshots__/snapshot.spec.js.snap
I need to reuse this table item component in the WalletConnect modal.
> feat: custom panel table item component

- src/utils/userDevices.ts
Firefox is not requesting camera access permission
> fix: camera permission request on ff

- src/popup/locales/en.json
- src/popup/plugins/veeValidate.ts
> fix: improve input error message & throttle balance updating

- capacitor.config.ts
- ios/App/App/Info.plist
- src/manifest.json
- src/popup/locales/cn.json
- src/popup/locales/de.json
- src/popup/locales/en.json
- src/popup/locales/es.json
- src/popup/locales/fr.json
- src/popup/locales/it.json
closes #3089 
also removed unused translation entry
> chore: use Superhero Wallet as app name

- src/composables/maxAmount.ts
- src/composables/multisigTransactions.ts
- src/constants/stubs.ts
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/TransactionDetailsBase.vue
- src/popup/components/TransferSend/TransferReviewBase.vue
- src/popup/locales/en.json
- src/popup/pages/MultisigProposalDetails.vue
- src/protocols/aeternity/components/TransferReview.vue
- src/protocols/aeternity/components/TransferSendForm.vue
- src/protocols/aeternity/config.ts
- src/protocols/aeternity/views/TransactionDetails.vue
- src/types/index.ts
fixes #2031,
fixes #3040,
part of #3057
> Improve total calculation transfer modal

- src/popup/components/AccountInfo.vue
- src/popup/components/AddressTruncated.vue
- src/popup/components/Avatar.vue
> fix: alignment on AccountInfo

- src/popup/pages/MultisigProposalDetails.vue
- src/protocols/aeternity/components/TransferReview.vue
> Fix multisig issues

- src/popup/components/TransferQRCodeGenerator.vue
- src/protocols/aeternity/components/TransferReview.vue
> fix(fungible-token): be able to send big amount

- src/popup/components/AccountInfo.vue
> fix: long names extend beyond container

- src/popup/components/Modals/ConfirmTransactionSign.vue
> fix: show gasCost if exists

- src/popup/components/QrCode.vue
> fix: update qr code when value changes

- src/popup/components/AddressTruncated.vue
> fix: remove incorrect component prop

- src/composables/pendingMultisigTransaction.ts
fixes #2913 
https://github.com/aeternity/ga-multisig-contract/blob/master/contracts/SimpleGAMultiSig.aes#L214
> fix(multisig): show correct revoke info

- src/composables/transactionData.ts
- src/popup/components/LatestTransactionsCard.vue
- src/popup/components/TransactionListItem.vue
closes #3084
Latest Transactions list remains unchanged by this
> feat: show fee in transaction list for token transfers

- src/composables/addressBook.ts
- src/constants/common.ts
- src/popup/components/AddressBook/AddressBookFilters.vue
- src/popup/components/AddressBook/AddressBookItem.vue
- src/popup/components/AddressBook/AddressBookList.vue
- src/popup/components/Modals/AddressBookAccountSelector.vue
- src/popup/components/TransferSend/TransferSendRecipient.vue
- src/popup/locales/en.json
- src/popup/pages/AddressBook.vue
- src/popup/router/modals.ts
> feat(address-book): send to contact

- src/popup/components/InputField.vue
- src/popup/components/form/FormTextarea.vue
- src/popup/locales/en.json
- src/popup/pages/PermissionManager.vue
> feat: improve character counter UI

- src/popup/components/Modals/AddressBookAccountSelector.vue
- src/popup/components/Modals/MultisigVaultCreate.vue
> feat: add addressBook selector to multisig creation form

- src/popup/components/InputAmount.vue
- src/popup/components/InputSelectAsset.vue
missed in https://github.com/superhero-com/superhero-wallet/pull/3122
> fix: be able to select from account assets only

- README.md
- docs/deep-link-schema.md
> docs: add a deep link schema

- src/popup/locales/en.json
> fix: add missing wording

- src/popup/locales/en.json
> chore: update validation wording

- src/popup/components/Modals/MultisigProposalConfirmActions.vue
> fix: align revoke icon correctly

- src/popup/pages/Names/AuctionList.vue
> refactor(aens): use v3 endpoint in auctions

- src/popup/locales/en.json
> fix: airgap import text

- android/app/src/main/AndroidManifest.xml
- src/composables/walletConnect.ts
- src/popup/components/Modals/WalletConnectModal.vue
- src/popup/router/index.ts
> feat(wallet-connect): support deeplinks

- src/popup/components/AccountDetailsBase.vue
- src/popup/components/AddressBook/AddressBookFilters.vue
- src/popup/components/HorizontalScroll.vue
- src/protocols/aeternity/views/AccountDetails.vue
- Update buttons order to match figma
- Fix horizontal scroll to work with mouse wheel even without `shift` key
- User can scroll by dragging
closes #3199
> feat: move browser button before faucet & buy

- src/popup/locales/en.json
> refactor: improve offline mode tabs wording

- src/background/bgPopupHandler.ts
- src/background/index.ts
- src/composables/accounts.ts
- src/composables/auth.ts
- src/composables/secureStorageRef.ts
- src/constants/common.ts
- src/lib/SecureMobileStorage.ts
- src/offscreen/popupHandler.ts
- src/offscreen/utils.ts
- src/popup/components/Modals/AccountImport.vue
- src/popup/pages/SecureLoginSettings.vue
- src/popup/router/index.ts
- src/types/index.ts
- src/utils/crypto.ts
- src/utils/session.ts
- tests/e2e/support/commands.js
related comments
- https://github.com/superhero-com/superhero-wallet/pull/3231#discussion_r1758062888
- https://github.com/superhero-com/superhero-wallet/pull/3231#discussion_r1758182189
- https://github.com/superhero-com/superhero-wallet/pull/3231#discussion_r1756500405
> feat: do not keep salt and iv with encryption key

- src/protocols/aeternity/composables/aeTippingBackend.ts
> chore: disable backend health check

- src/protocols/aeternity/libs/AeAccountHdWallet.ts
> feat(aeternity): skip confirm modal for transactions created by wallet

- src/popup/pages/AddressBookForm.vue
fixes https://github.com/superhero-com/superhero-wallet/issues/3274
> fix(firefox): show qr code for addrees book item correctly

- src/popup/components/InputField.vue
> refactor: set input type only for password field

- src/popup/pages/SeedPhraseVerifySettings.vue
> fix: be able to verify seed phrase

- src/popup/components/Modals/PrivateKeyImport.vue
> fix: be able to import private key account if airGap account imported

- src/composables/auth.ts
- src/utils/common.ts
> Fix password update

- src/popup/pages/Address.vue
- src/popup/pages/JwtSign.vue
- tests/e2e/integration/deeplinks.cy.js
> fix(deep-link): be able to return `networkId`

- src/popup/locales/en.json
- src/popup/pages/Assets/AssetDetailsInfo.vue
fixes https://github.com/superhero-com/superhero-wallet/issues/3371
> refactor: adjust asset details page

- src/protocols/aeternity/helpers/transactionTokenInfoResolvers.ts
> fix: show assets for sell transactions correctly

- src/composables/transactionData.ts
- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/components/TransactionDetailsPoolTokens.vue
- src/popup/components/TransactionLabel.vue
- src/popup/components/TransactionTagList.vue
- src/protocols/aeternity/views/TransactionDetails.vue
missed in https://github.com/superhero-com/superhero-wallet/pull/3055,
fixes #3391
> fix(aeternity): show correct allowance transaction info

- src/constants/common.ts
- src/popup/components/Modal.vue
- src/popup/components/Modals/AssetSelector.vue
- tests/e2e/support/commands.js
> perf(asset-selector): do not render all assets at once

- src/popup/pages/Assets/AssetDetailsInfo.vue
> fix: show correct market cap coin info

- src/utils/common.ts
fixes https://github.com/superhero-com/superhero-wallet/issues/3418
> fix: be able to import private key account on mobile app

- src/popup/components/AddressBook/AddressBookList.vue
- src/popup/components/InputField.vue
- src/popup/components/Modals/ProtocolSelect.vue
- src/popup/components/Modals/SetPassword.vue
> feat: add new data cy ids

- src/composables/modals.ts
- src/popup/App.vue
- src/popup/components/Modals/PasswordLogin.vue
- src/popup/components/Modals/ResetWalletModal.vue
- src/styles/variables.scss
> Do not show sensitive content if not authenticated 

- src/lib/logger.ts
- src/popup/locales/en.json
- src/popup/pages/Address.vue
- src/popup/pages/JwtSign.vue
- src/popup/pages/SignMessage.vue
- src/popup/pages/SignTransaction.vue
- src/protocols/aeternity/components/TransferReview.vue
- tests/e2e/support/commands.js
> fix(deep-link): show internal error modal before redirect

- src/popup/components/ConnectionStatus.vue
- src/popup/components/FixedScreenFooter.vue
- tests/unit/import-account.spec.js
> feat: padding on fixed footer to fix overlay issue with status

- src/protocols/aeternity/composables/aeMiddleware.ts
- src/utils/common.ts
> feat: show internal `spendTx` correctly

- src/popup/components/AccountDetailsBase.vue
> fix: show private key only if wallet knows it

- src/composables/transactionData.ts
- src/popup/components/TransactionCallDataDetails.vue
- src/popup/components/TransactionDetailsBase.vue
- src/protocols/ethereum/helpers/index.ts
> fix: show asset as unrecognized if so

- src/constants/common.ts
- src/protocols/aeternity/config.ts
> Use new avatars, bug report urls

- src/protocols/aeternity/components/TransferReview.vue
> fix: be able to send custom aex9 tokens

- src/constants/environment.ts
- src/popup/App.vue
- src/popup/components/AccountDetailsBase.vue
- src/popup/components/AccountInfo.vue
- src/popup/components/Avatar.vue
- src/popup/components/DefaultPagesRouter.vue
- src/popup/components/Modal.vue
- src/popup/pages/Assets/AssetDetails.vue
- src/popup/pages/Names/Auction.vue
- src/protocols/aeternity/views/AccountDetailsNames.vue
part of #3235,
Both commits should be reverted when chromium issue is fixed.
> Disable transitions in chrome

- src/popup/components/Assets/AssetListItem.vue
- src/popup/components/TokenAmount.vue
- src/popup/components/TokenAmountFormatted.vue
- src/popup/components/TransactionAssetRows.vue
> feat: handle long numbers

- src/popup/locales/en.json
- src/protocols/aeternity/config.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/protocols/aeternity/types.ts
- src/protocols/bitcoin/libs/BitcoinAdapter.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
> feat: be able to set custom explorer url

- src/composables/permissions.ts
- src/popup/components/NetworkRow.vue
- src/popup/pages/Settings.vue
> Fix supported blockchain marketing

- src/content-scripts/inject.ts
- src/content-scripts/inpage.ts
- src/protocols/ethereum/config.ts
- src/protocols/ethereum/libs/EthereumRpcMethodsHandler.ts
> Fix EVM methods handling

- src/composables/connectionStatus.ts
- src/composables/currencies.ts
- src/popup/App.vue
- src/popup/components/ConnectionStatus.vue
- src/popup/components/InputAmount.vue
- src/popup/components/TotalWalletAmount.vue
- src/popup/components/buttons/BtnIcon.vue
- src/popup/locales/en.json
> Handle no fiat information

- src/composables/transactionList.ts
> fix: show latest transaction in account transaction list

- src/composables/networks.ts
- src/constants/common.ts
- src/popup/components/Header.vue
- src/popup/components/InputField.vue
- src/popup/components/Modals/Default.vue
- src/popup/components/buttons/BtnHelp.vue
- src/popup/locales/en.json
- src/popup/pages/Settings.vue
- src/popup/pages/TokenSalesSettings.vue
- src/popup/router/routeNames.ts
- src/popup/router/routes.ts
- src/protocols/aeternity/composables/aeTokenSales.ts
- src/protocols/bitcoin/components/TransferSendForm.vue
> feat: be able to add custom token sale url

- src/composables/walletConnect.ts
> feat(wallet-connect): propagate account change

- src/popup/components/TransferSend/TransferSendRecipient.vue
- src/popup/components/form/FormAccountInput.vue
> feat: UI improvement on single recipient

- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/popup/locales/en.json
- tests/e2e/integration/receive.cy.js
> feat: sign transaction despite not enough balance

- src/composables/accountSelector.ts
- src/popup/components/AvatarWithChainName.vue
- src/popup/components/TransactionDetailsBase.vue
- src/popup/components/TransferSend/TransferReviewBase.vue
- src/popup/components/TransferSend/TransferSendRecipient.vue
- src/protocols/aeternity/components/TransferSignedTxReview.vue
closes #3507 
Additionally: 
- Fixes background color issue in `Transaction details`
- In the latest transactions the background color of `own multisig account` has been added, as it was missing
> feat: account name on transaction review

- src/popup/components/Modals/ConfirmTransactionSign.vue
> fix: be able to sign transaction with new/empty account

- src/popup/components/Modals/ConfirmTransactionSign.vue
- src/protocols/aeternity/composables/aeTokenSales.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/types/index.ts
> perf(token-sale): load only necessary token info

- package-lock.json
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/160,
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/159
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/153
fixes https://github.com/superhero-com/superhero-wallet/security/dependabot/152
> build: run npm audit fix

- src/popup/components/Modals/ConfirmTransactionSign.vue
> fix: do not allow to sign transaction while loading info

- src/composables/latestTransactionList.ts
- src/composables/transactionList.ts
- src/popup/components/TransactionOverview.vue
- src/protocols/aeternity/composables/aeMiddleware.ts
- src/protocols/aeternity/helpers/index.ts
- src/protocols/aeternity/libs/AeternityAdapter.ts
- src/types/index.ts
> perf: do not wait for a tipping response with a huge delay

- src/popup/components/Modals/ShareAddressBase.vue
> fix: wrong display of account and share link

- package-lock.json
- src/composables/transferSendForm.ts
- src/lib/RouteQueryActionsController.ts
- src/popup/popup.ts
- src/protocols/aeternity/components/TransferSendForm.vue
- src/protocols/bitcoin/components/TransferSendForm.vue
- src/protocols/ethereum/components/TransferSendForm.vue
- tests/e2e/integration/deeplinks.cy.js
- tests/e2e/support/commands.js
- tests/unit/composables/open-scan-qr-modal.spec.js
> fix: send popup not opening the second time

- src/protocols/ethereum/config.ts
- src/protocols/ethereum/helpers/index.ts
- src/protocols/ethereum/libs/EthereumAdapter.ts
- src/protocols/ethereum/libs/EthereumRpcMethodsHandler.ts
- src/protocols/ethereum/libs/EtherscanService.ts
> refactor: migrate to etherscan v2

- src/composables/addressBook.ts
- src/popup/locales/en.json
- src/utils/common.ts
> fix(android): be able to export address book

- src/composables/permissions.ts
- src/composables/walletConnect.ts
- src/popup/pages/Address.vue
- src/popup/pages/Popups/Connect.vue
- src/popup/pages/Popups/ConnectBase.vue
- src/protocols/solana/libs/SolanaAdapter.ts
- tests/unit/popup/pages/Popups/Connect.spec.ts
- tests/unit/popup/pages/Popups/ConnectBase.ae.spec.ts
> Fix Connect popup

- src/constants/environment.ts
- src/popup/App.vue
- src/popup/components/AccountDetailsBase.vue
- src/popup/components/AccountInfo.vue
- src/popup/components/Avatar.vue
- src/popup/components/DefaultPagesRouter.vue
- src/popup/components/Modal.vue
- src/popup/pages/Assets/AssetDetails.vue
- src/popup/pages/Names/Auction.vue
- src/protocols/aeternity/views/AccountDetailsNames.vue
Previously chromium had a bug for more details look here https://github.com/superhero-com/superhero-wallet/issues/3235.
Chromium have fixed that issue.
> refactor: enable transitions on chrome
