superhero-com/superhero-wallet

src/lib/rpcWallet.js, webpack.config.js
I'm working currently on webpack configs, for me would be easier to simplify them a bit.
- can we drop `EXTENSION_RUNNING_IN_TESTS_BROWSER`?
- can we build apps for e2e tests separately?
=> Simplify e2e configs

src/manifest.js, src/notifications.js, src/phishing/App.vue, src/popup/App.vue, src/popup/router/components/AccountInfo.vue, src/popup/router/components/BalanceInfo.vue, src/popup/router/components/CheckBox.vue, src/popup/router/components/ClaimTipButton.vue, src/popup/router/components/Header.vue, src/popup/router/components/PendingTxs.vue, src/popup/router/components/SidebarMenu.vue, src/popup/router/components/TransactionFilters.vue, src/popup/router/components/TransactionItem.vue, src/popup/router/components/Welcome.vue, src/popup/router/pages/AboutSettings.vue, src/popup/router/pages/Account.vue, src/popup/router/pages/Index.vue, src/popup/router/pages/Intro.vue, src/popup/router/pages/Notifications.vue, src/popup/router/pages/Receive.vue, src/popup/router/pages/Retip.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/SuccessTip.vue, src/popup/router/pages/TermsOfService.vue, src/popup/router/pages/TipPage.vue, src/redirect/App.vue, webpack.config.js
`browser.runtime.getURL` can't be used in css, so I proposing to avoid it by using relative paths (they works both in extensions and Cordova).
Importing of svg by default as Vue components is not works in css, so I proposing to enable importing as a component explicitly by adding `?vue-component`.
Also, these changes is needed for web version of the wallet, because there we should avoid the `popup` folder in `dist` and use absolute paths.
=> Explicit assets import

.travis.yml
Actually, it doesn't make a significant difference (~2 minutes faster). Just Travis won't be needed to run `npm ci` three times.
=> travis: Combine into single job to speedup testing

config.xml
Made according to https://cordova.apache.org/howto/2020/03/18/wkwebviewonly.html
Supposed to fix this warning:
> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.
=> Make Cordova to don't use UIWebView on iOS

src/common/base.scss, src/common/extension.scss, src/popup/router/components/AccountInfo.vue, src/popup/router/components/BalanceInfo.vue, src/popup/router/components/Button.vue, src/popup/router/components/Popup.vue, src/popup/router/components/SidebarMenu.vue, src/popup/router/components/Textarea.vue, src/popup/router/pages/GeneralSettings.vue, src/popup/router/pages/Index.vue, src/popup/router/pages/Receive.vue, src/popup/router/pages/SignTransaction.vue, src/popup/router/pages/SuccessTip.vue
Closes this issue:
One moment is questionable: 
1. After fixes we have different color of `Current language` here (prev. it was overrided by `:not:not:not` with `$white-color`), but it was set in `.sett_info`  intentionally.
2. Same with button: all other buttons in project have `$button-text-color` text color, and in this case it was overrided by `:not:not:not` as well.
Also this colors now match up with designs:
=> Avoid overriding of font-family and color for every node

.eslintrc.js, src/popup/router/components/AmountSend.vue, src/popup/router/components/Input.vue, src/popup/router/components/PendingTxs.vue, src/popup/router/pages/Popups/PopupSignTx.vue, src/popup/router/pages/Retip.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/TipPage.vue, tests/e2e/integration/tip.js
Airbnb's eslint disallows `window.isNaN` because of its confusing behavior: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN#Description
=> Use Number.isNaN instead of isNaN, enable "no-restricted-globals" eslint rule

src/popup/locales/en.json, src/popup/router/components/BoxButton.vue, src/popup/router/components/ClaimTips.vue, src/popup/router/components/Loader.vue, src/popup/router/components/TransactionItem.vue, src/popup/router/pages/Account.vue, src/popup/router/pages/Receive.vue, src/popup/router/pages/Retip.vue, src/popup/router/pages/TipPage.vue, src/popup/utils/helper.js, tests/e2e/integration/tip.js, tests/e2e/support/commands.js
* Show claim button in mobile but disabled and on click show modal with message
* Add more info in show seed phrase page
* Disable confirm modal when send tip to unverified url until have endpoint returning problematic for claim urls
* Fix of text in edit tip details button
* Show better error message when backend payfortx times out (when claim medium url for instance)
* Remove cofirm url button when manually enter tip url
* Fix problem with showing amount when tx is name claim
=> Fixes from test report

src/popup/router/components/ClaimTips.vue
This was fixed here https://github.com/aeternity/superhero-wallet/commit/2cddd8ac66c7c0e285632fd9756eb527d7441efa, but maybe after merge or conflicts resolved is wrong again
=> Fix typo in cache invalidate URL

src/popup/router/pages/ClaimTips.vue
closes #244 
Issue was the invalidate routes should be invoked by `GET` instead of `POST`
=> Fix 404 after claim

src/background.js, src/lib/rpcWallet.js, src/popup/router/pages/Popups/Connect.vue
* Fix problem in Firefox with openning multiple duplicates of connection popup
* Make method shouldOpenPopup with promises
* Get active tabs and remove if there is opened connection popup for url
* Cleanup and refactor
=> Prevent multiple permission request popups for the same url

src/inject.js
Looks like regex for matching `.chain` names in content script was causing Firefox to slow down. It should be tested well if claim with `.chain` names works fine.
=> Optimize regex for match .chain names. More attempts to find ak_/.chain name

package-lock.json, package.json
Roll back SDK to `7.1.1` due to browser detection issues
=> Roll back to sdk 7.1.1

src/inject.js
https://github.com/aeternity/aepp-base/pull/147
this code wasn't working properly in ~0.55% of cases:
```js
> new Array(10000).fill()
.map(() => Crypto.generateKeyPair().publicKey.length)
.reduce((p, n) => ({ ...p, [n]: (p[n] || 0) + 1 }), {})
{ '51': 55, '52': 5021, '53': 4924 }
```
=> inject: Fix detection of ae address

src/lib/wallet.js
I have to add this ugly confirm to be able to test reverse iframe on develop branches. The user won't see it in the production version because there superhero.com is whitelisted.
=> Confirm connection to unknown origins

src/content-scripts/twitter.js
Closes #408.
I propose to not align "topic starter" tweet and "reply" tweets tip buttons, and instead of that use their natural flex flow. That way we will avoid using "magic" constants.
=> twitter.js: Fix tip button alignment

src/content-scripts/twitter.js
If we not logged in some styles still applied to the tweets without a button rendered.
=> twitter.js: Don't apply style changes if not logged in

package.json
I propose to use `-d` flag for webpack in dev mode. It's much easier to debug with source-maps.
It turns this
to
=> Enable development flag in devmode

src/content-scripts/twitter.js
Potentially closes #411.
I can't reproduce this issue, but in the case @marc0olo mentioned we should cut part after `/status/numbers/...`, I think this should fix this issue.
=> twitter.js: Match only tweet id in tweet link

src/popup/router/components/AmountSend.vue, src/popup/router/components/InviteItem.vue, src/popup/router/pages/Invite.vue, src/popup/router/pages/InviteClaim.vue, src/popup/router/pages/Names/AuctionBid.vue, src/popup/router/pages/Popups/SignTx.vue, src/popup/router/pages/Retip.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/Tip.vue, src/popup/router/routes/index.js, src/store/modules/invites.js
closes https://github.com/aeternity/superhero-ui/issues/724
will work much better after implementing of #378 
some exceptions are not displayed because of #437
It has a regression: I proposing to don't persist balances because it complicates state and I think it is enough to have this fancy feature only on the main screen. Otherwise, I propose to implement a general mechanism of balance caching instead of doing the same in different views.
Also, it has a security/privacy issue: shared private key will be exposed to owners of a web server. It may be solved by putting it in a hash part of the URL, but it needed to investigate how to handle this in Cordova because we are using hash navigation there.
=> Allow to claim tokens by invite link

src/popup/popup.js, src/popup/router/index.js, src/popup/router/modals.js
In the latest release, we have a bug: if the user opens https://wallet.superhero.com/aboutSettings, then press the back arrow button it will result in the exception:
> TypeError: Cannot read property 'path' of undefined
at a.back (popup.js:107)
at He (popup.js:27)
at SVGSVGElement.r (popup.js:27)
at SVGSVGElement.i._wrapper (popup.js:27)
This happens because `afterEach` hook registered by `vuex-router-sync` is not getting executed the first time because it is shifted by another unregistered hook.
=> Header: Fix back button

src/popup/router/components/AmountSend.vue, src/popup/router/components/BalanceInfo.vue, src/popup/router/components/InviteItem.vue, src/popup/router/components/TransactionItem.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/SuccessTip.vue, src/popup/router/pages/Tip.vue, src/store/getters.js, tests/e2e/integration/amount-send.js, tests/e2e/integration/withdraw.js
inspired by the changes in #466 
#466 introduces currency symbols in several places, having `currentCurrency` getter that is just an uppercased current currency, it is quite easy to introduce currency symbols in the whole application.
I'm proposing to merge this PR firstly and to rebase #466 on the top of it.
=> Use currency symbols instead of abbreviations

src/popup/utils/openUrl.js
This quick fix potentially closes #493 as we won't open any links inside iframe web-wallet.
=> Always use window.open on links inside iframe web wallet

src/popup/router/components/TransactionItem.vue, src/popup/router/pages/Transactions.vue
All the transactions were shown with sign `Received`, no `sender` or `receiver` address provided, also did not sort.
Weird, because in README file https://github.com/aeternity/ae_mdw all the receiver or sender type have `_id` in the end.
=> Fix displaying of transactions

src/popup/router/components/TransactionItem.vue, src/popup/router/pages/Send.vue
Tx preview when clicking the eye icon was leading to the middleware API URL
Instead of the explorer URL (middleware UI) specified in the constants file
Fixes #504
=> Replaced middlewareUrl with explorerUrl

src/lib/rpcWallet.js, src/store/getters.js
first commit fixes `Error: Attempting to use a disconnected port object`,
second fixes #523
=> Fix logout/login related issues

config.xml
Before there was used Swift 4 and the error was:
> 'openSettingsURLString' has been renamed to 'UIApplicationOpenSettingsURLString'
in https://github.com/bitpay/cordova-plugin-qrscanner/blob/b62efb64801ba0b830f0aac556935c0978d2fb98/src/ios/QRScanner.swift#L471
I have faced this error trying to build 0.3.3 release using Xcode 12.0.1
=> cordova ios: Fix compilation error by choosing a different swift version

src/background.js, src/lib/deeplink-handler.js, src/manifest.js, src/popup/utils/openUrl.js
needed for https://github.com/aeternity/superhero-button/pull/24
In general it may be used as a light way to integrate superhero wallet (without dependency on sdk). But I'm not sure is it a good UX to open extension page in a usual tab (at it is implemented now). Technically we can avoid that but with an additional effort.
This may be tested by opening links from https://github.com/aeternity/superhero-wallet/blob/develop/tests/pages/index.html
Also, it makes the extension to support invite links 🤔
=> Handle deeplinks on extension side

src/popup/router/components/ClaimTipButton.vue, src/popup/router/components/TransactionItem.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/SuccessTip.vue, src/popup/utils/openUrl.js
reverts #495 
The thing is that window.parent is always truthy:
> If a window does not have a parent, its parent property is a reference to itself.
https://developer.mozilla.org/en-US/docs/Web/API/Window/parent
Would be better to use IN_FRAME the next time. Forcing openUrl to use a new tab in the web version of wallet breaks deeplink flow. To address #493 I'm proposing explicitly specify that the explorer and ui should be opened in a new tab, but keeping the ability to open deeplink in the same tab that is used in Meet.
closes https://github.com/aeternity/jitsi-meet/issues/259
=> hotfix: Open deeplink callbacks in current tab even in iframe use case

src/lib/rpcWallet.js
Without opening the popup, the init function is called only once, and for some reason, it wasn't adding the account in that case. Superhero-ui was detecting the extension but wasn't able to use it because of the lack of an account. This PR is supposed to fix this case.
=> Add account on the first init call

src/popup/router/components/UserAvatar.vue
| Before | After |
|---|---|
| <img width="220" alt="Screenshot 2020-10-28 at 09 27 46" src="https://user-images.githubusercontent.com/9007851/97400294-f02adc80-18ff-11eb-802e-b7274dce9702.png"> | <img width="220" alt="Screenshot 2020-10-28 at 09 27 51" src="https://user-images.githubusercontent.com/9007851/97400305-f456fa00-18ff-11eb-87cb-d1fb9ace8508.png"> |
=> UserAvatar: Don't collapse the image

src/popup/router/pages/Notifications.vue
Fixes error:
> Invalid prop: type check failed for prop "address". Expected String with value "null", got Null 
found in
---> <UserAvatar> at popup/router/components/UserAvatar.vue
<NotificationItem> at popup/router/components/NotificationItem.vue
<Notifications> at popup/router/pages/Notifications.vue
<AeMain> at src/components/aeMain/aeMain.vue
<App> at popup/App.vue
<Root>
When looking at "claimed your retip" notification with has `sender` equal to `null`.
depends on https://github.com/aeternity/superhero-avatars/pull/2
=> Fallback to empty string if sender is null

src/content-scripts/inject.js
The idea is to use deeplinks instead, it may have a worse UI but this is much flexible. This would break the existing superhero-button installations, so I'm not sure when it the best time to merge it.
=> Remove superhero-button click listener

src/popup/utils/constants.js
The current name extend interval is 100 blocks. This means that the wallet will ask to extend names every 5 hours (100 blocks * 3 minutes/block / 60 minutes/hour). This seems to be super frequent, assuming that name is extended for 104 days (50k blocks). We need to find a balance between annoying users with frequent notifications and making less probable the loosing of names by users that open wallet several times in a year. 
Here are my assumptions about when the wallet should remind the user to extend name depending on his activity:
| Average wallet opening interval | Need to remind to extend name after (104 days - opening interval) |
|---|---|
| 1 day | 103 days |
| 1 week | 97 days |
| 1 month | 74 days |
| 2 months | 44 days |
| 3 months | 14 days |
| 4 months | AENS shouldn't be …
=> Increase auto extend name blocks interval

src/popup/router/components/Avatar.vue
| Before | After |
|---|---|
| Not rounded corners | Normal |
| <img width="305" alt="Screenshot 2020-11-22 at 22 44 00" src="https://user-images.githubusercontent.com/9007851/99915357-44b15400-2d14-11eb-8da0-3c4843724d1b.png">| <img width="305" alt="Screenshot 2020-11-22 at 22 43 55" src="https://user-images.githubusercontent.com/9007851/99915360-467b1780-2d14-11eb-9b10-96bb67f45e83.png">  |
| Shrinked | Normal |
| <img width="338" alt="Screenshot 2020-11-22 at 22 41 27" src="https://user-images.githubusercontent.com/9007851/99915381-627eb900-2d14-11eb-9a2c-9809a0f241d7.png"> | <img width="338" alt="Screenshot 2020-11-22 at 22 41 32" src="https://user-images.githubusercontent.com/9007851/99915361-4713ae00-2d14-11eb-9840-5bc54221f09f.png"> |
Stan has changed Avatar's `object-fit` to …
=> Fix Avatar component

src/popup/popup.js
This reverts commit d06afa2c4c1d00bda9f9ed2d21a7ecc763578bb6.
This fixes the error on "Send Tip" screen:
> logger.js?45e3:15 callback for immediate watcher "function () {
return _this.sdk;
}"
logger.js?45e3:16 TypeError: Expected a function
at baseDelay (_baseDelay.js?5a79:16)
at eval (defer.js?d7ab:23)
at apply (_apply.js?9943:15)
at eval (_overRest.js?6c13:32)
at VueComponent._this.$watch.immediate (popup.js?4eca:22)
at VueComponent.Vue.$watch (vue.runtime.esm.js?e832:4949)
at eval (popup.js?4eca:16)
at new Promise (<anonymous>)
at VueComponent.watchUntilTruly [as $watchUntilTruly] (popup.js?4eca:14)
at _callee$ (Tip.vue?fe7f:175)
The wrapping function is necessary because, in the case of the immediate, watcher is called in sync, earlier than `unwatch` value is evaluated. `defer` …
=> Revert "popup: Remove extra wrapper around unwatch"

src/store/plugins/persistState.js
Hack explanation that was missed in https://github.com/aeternity/superhero-wallet/pull/108#discussion_r462054888:
> It's generally not possible to store other types, such as Function, Date, RegExp, Set, Map, ArrayBuffer, and so on. Some of these unsupported types will restore as an empty object, and some cause set() to throw an error.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/set
I assume that `cloneDeep` converts reactive vue variables to plain objects that become compatible with Firefox's storage.
=> persistState: Explicitly mark that cloneDeep hack is needed for Firefox

src/popup/router/pages/ImportAccount.vue
I propose to change behaviour of loading in the ImportAccount page
|Before|After|
|---|---|
|![impot](https://user-images.githubusercontent.com/9008074/101346431-3ea2a200-38d4-11eb-8733-b8ec1609990e.gif)|![import2](https://user-images.githubusercontent.com/9008074/101346571-7873a880-38d4-11eb-92dc-9f82be9c9f29.png)|
=> ImportAccount: Show only Loading component on loading

src/lib/wallet.js
Fixer error:
> [vuex] state field "sdk" was overridden by a module with the same name at "sdk"
The overlapping of `state.sdk` variable and `sdk` module is completely breaks sdk in iframe mode.
=> Fix sdk of wallet in reverse frame

src/background/wallet.js, src/lib/wallet.js
This is an interesting bug(?) related to how babel transpile await functions https://github.com/babel/babel/issues/4219.
As I understand, if you spread `...args` in async function it will only be inserted if it is used somehow inside. That's strange, because we had getting last element of args array `args[args.length - 1]`, but transpiler hasn't inserted it, so when I've changed it to `args.pop()` it worked 🤷.
Because of this bug `address` permissions weren't working correctly, so I propose to include it to release if it pass @davidyuk review.
=> wallet.js: Affect args to make it inserted into function

src/store/modules/permissions.js
This fixes missed bug with iframe permissions with checking the result of address request popup. Extension popup returns `true` or `false` depends on user choice, but iframe popup returns `undefined` and it should be handled with try/catch.
=> permissions.js: Add try/catch for iframe connection popup

src/lib/wallet.js
There was a CORS header issue with the hosted middleware on the mainnet. It was worked around with #741.
As this is now resolved in the hosted mdw - this PR will revert the changes and fallback to normal mdw swagger read and connection.
=> Remove middleware CORS issue workaround

.github/workflows/main.yml
> On February 15th, GitHub Actions will remove support for referencing actions using the shortened version of a git commit SHA. This may cause some workflows in your repository to break. To fix these workflows, you will need to update the action reference to use the full commit SHA.
=> ci: don't use deprecated short sha

src/styles/global.scss
I've decided to move this fix out of notifications PR because it affects other screens.
It fixes issue mentioned by @CedrikNikita in first gif here https://github.com/aeternity/superhero-wallet/pull/716#pullrequestreview-573009116
Because of this issue notifications, activity, names, terms of use, privacy policy (maybe more) screens were moving left a little bit because of 1px width transparent (😆) scrollbar appearance.
=> Don't display scrollbar on blink and webkit engines

package.json
https://github.com/aeternity/superhero-wallet/pull/775/commits/8cd9d2b100e2b513426cbe97de6c14fb9519dc2e
Start using commit lint from first valid commit.
Moving this commit directly to develop instead the release branch, so CI does not break until we've released 0.5.1.
Thanks @etharner !
=> Run commitlint from first valid commit

src/styles/global.scss
I propose to revert 7755be64 because it 
1) prevents scrolling in extension in Chrome
2) we have new scrollbar designs
=> fix(global): revert scrollbar width until rebranding

src/store/plugins/names.js
fixes this issue
```
Uncaught (in promise) TypeError: Cannot read property 'preferredChainName' of undefined
at _callee$ (names.js?2510:107)
at tryCatch (vue-tour.umd.js?1415:1940)
at Generator.invoke [as _invoke] (vue-tour.umd.js?1415:2166)
at Generator.prototype.<computed> [as next] (vue-tour.umd.js?1415:1992)
at asyncGeneratorStep (names.js:61)
at _next (names.js:63)
```
=> names: Handle the default name responce correctly

src/popup/router/components/FungibleTokens/TokensListItem.vue, src/popup/router/pages/FungibleTokens/TokenDetails.vue
ref https://github.com/aeternity/superhero-wallet/pull/775#pullrequestreview-583217133
change log:
*  use `ellipseStringMid` for long fungible token names in list and details views
=> Fix long FT names go outside borders

package-lock.json, package.json, src/popup/locales/en.json, src/popup/router/index.js, src/popup/router/pages/Tip.vue, src/popup/router/routes/index.js
fixes #260
change log:
* forked a patched fork of `cordova-plugin-openwith` and adjusted hardcoded config to support only text sharing
* added URL prop to Tip page
* route to Tip page with URL prefilled on share intent
dev notes:
* run `cordova prepare` to init the new plugin for iOS/Android
screenshots:
=> Tip shared URL on iOS/Android

CHANGELOG.md, config.xml, package-lock.json, package.json
This was required because of some faulty builds in Apple's TestFlight. It does not allow replacing builds, so we needed to bump up the version number.
=> Bump to 0.5.4

src/popup/utils/helper.js
It's hard to reproduce but consider my previous screenshoots in issue it can be fixed this way.
Closes #788.
=> fix(helper): return undefined if no response field

src/popup/router/components/AccountInfo.vue, src/popup/router/components/FungibleTokens/TokensListItem.vue, src/popup/router/components/Header.vue, src/popup/router/components/SidebarMenu.vue, src/popup/router/components/TruncateMid.vue, src/popup/router/pages/FungibleTokens/TokenDetails.vue, src/popup/router/pages/Names/List.vue, src/popup/utils/helper.js, tests/e2e/integration/names.js, tests/e2e/support/commands.js
Previous aproach wasn't flexible enough:
In the old version there is no difference bwetween wide letters and not wide.
Even if the letters are not wide and the whole string could fit in the screen, it still would be truncated to the amount.
Test names are the same size in old and new versions
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/107723371-ad650700-6d2c-11eb-9dce-5c7c175a74da.png)|![image](https://user-images.githubusercontent.com/9008074/107723376-afc76100-6d2c-11eb-9664-019023668288.png)|
=> Improve truncating of a long strings

src/popup/router/components/Modals/QrCodeReader.vue, tests/e2e/integration/withdraw.js
fixes #833
QA:
* QR code read related functionality must be tested well on all platforms
=> Fix blank screen after splash on iOS

src/phishing/App.vue, src/popup/App.vue, src/popup/router/components/RecentTransactions.vue, src/popup/router/pages/ClaimTips.vue, src/popup/router/pages/CommentNew.vue, src/popup/router/pages/FungibleTokens/TokenDetails.vue, src/popup/router/pages/Names/AuctionBid.vue, src/popup/router/pages/Names/AuctionList.vue, src/popup/router/pages/Names/Details.vue, src/popup/router/pages/Names/List.vue, src/popup/router/pages/PermissionsDetails.vue, src/popup/router/pages/Popups/AskAccounts.vue, src/popup/router/pages/Popups/Connect.vue, src/popup/router/pages/Popups/MessageSign.vue, src/popup/router/pages/Popups/SignTx.vue, src/popup/router/pages/Retip.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/SuccessTip.vue, src/popup/router/pages/Tip.vue, src/redirect/App.vue, tests/aepp/App.vue, tests/e2e/integration/amount-send.js
I think by default we should use `mounted` because:
- in `mounted` hook the component's DOM is available making a wider range of operations available
- `mounted` is not executed in SSR context, it is not related to this repository, but it seems to be a good habit to don't use `created` by default because of that
=> refactor: prefer 'mounted' hook instead of 'created'

package.json
This reverts commit 404972ea13d4d55f33d2fc402b88ff373012cac9.
I can't get the reasoning for changes made in #791. From my perspective reference to develop is better, because:
- running `lint:commit` I will get a short list of commit messages made by me, without commits already merged
- reference to develop makes it possible to move the setup to another repository without extra adjustments
=> fix(commitlint): revert run commitlint from first valid commit

src/popup/router/index.js
Prevent from new pages being opened in the same scroll position.
Demo of the issue:
=> Scroll to top on route change

webpack.config.js
This closes recently @Liubov-crypto issue in firefox https://github.com/aeternity/superhero-wallet/pull/910#pullrequestreview-617540107
This bug was in the wallet since #49.
The problem is in webpack config for extension-firefox. The chunk `redirect/redirect` hasn't been excluded from html build and therefore **if we weren't lucky** `redirect.js` was inserting **after** `popup.js` and it's `App.vue` was mounted to same `#app` div resulting to wrong page displaying.
As `redirect-chain-names` is using `redirect.html` nor `popup.html` we can exclude corresponding `redirect.js` from `popup.html`
We couldn't catch it cause we usually build extension only once and then hot-reloading it.
=> fix(firefox-redirect): exclude redirect.js from popup.html

src/popup/locales/en.json
> The “claim tips for this
URL” part could be “claim tips FROM this URL”.  Just a
grammar suggestion here. (Because, the way it is, it seems that tips
are being claimed in the name of URL X, not those that were sent to
URL X and are, colloquially speaking, there).
=> chore(locales): update urlToClaim text

src/popup/router/pages/SecuritySettings.vue, src/popup/router/routes/index.js
> When you select this from
the Settings menu, and go “show seed phrase” + “I’ve already
done this” it takes you back home instead of showing the Settings
menu again. Adds an unnecessary step in case you wish to continue
browsing the Settings menu.
=> refact(settings): redirect back to settings after backup seed

.eslintrc.js, src/popup/router/components/BalanceInfo.vue, src/popup/router/components/Modals/ClaimSuccess.vue, src/popup/router/components/Modals/ErrorLog.vue, src/popup/router/components/ThreeDotsMenu.vue, src/popup/router/components/Tour.vue, src/popup/router/pages/About.vue, src/popup/router/pages/LanguageSettings.vue, src/popup/router/pages/Popups/Connect.vue, src/popup/router/pages/Popups/MessageSign.vue, src/popup/router/pages/PrivacyPolicy.vue, src/popup/router/pages/SecuritySettings.vue, src/popup/router/pages/Send.vue, src/popup/router/pages/SignMessage.vue, src/popup/router/pages/TermsOfService.vue, tests/aepp/App.vue
I think this rule is too strict, it shouldn't make developers
- write `` to add a tilda
- write `{{ '~' }}` to add a tilda
- write `{{ $t('AE') }}` and `"AE": "AE"` in locale file to add "AE"
=> refactor: disable vue-i18n/no-raw-text rule

src/popup/router/pages/Names/Details.vue
I propose to include this to release #957.
Closes #946.
https://github.com/aeternity/superhero-wallet/pull/961/commits/078b1ab9fd87dd8d1b3172f4b87bebc646646289 was made because right after name is stopping being in "pending" state it's status is unavailable for some time.
=> Fix name details bugs

src/popup/App.vue, src/popup/router/components/NodeConnectionStatus.vue, src/popup/router/components/TabBar.vue, src/popup/router/components/TransactionFilters.vue, src/popup/router/pages/Popups/AexPopup.scss
Propose to merge this to #957.
This PR fixes this behavior on mobiles with big height screens:
=> fix(bottom-elements): display TabBar and Status at bottommost in mobile

src/store/actions.js
I suggest to return empty list if `Random access restricted` error will be returned from mdw until fix on our or their side.
This PR prevents this error spamming in many cases:
=> chore(tx): return empty tx list if getTxByAccount returns error

src/popup/router/components/AccountInfo.vue
This PR fixes issue with alignment of account info changing on name claiming and address copying
=> fix(account-info): fix alignment on copy and name claim

src/store/getters.js
related to #907.
Can be reproduced, if the loading of availableTokens would be slower than loading of transactions that have fungibleTokens inside.
=> fix(fungible-tokens): check if availableTokens are loaded

src/popup/router/pages/Names/Details.vue
This fixes reloading of name details page leading to watch before sdk init and corresponding error.
=> fix(details): block buttons and don't watch before sdk init

src/popup/router/components/DetailsItem.vue, src/popup/router/components/Modals/ConfirmTransactionSign.vue
`DetailsItem` and `CopyButton` couldn't work with `pointers` tx field because it's an array
=> fix(tx-pointers): fix name pointers field error in confirm tx modal

src/popup/router/components/MenuCarousel.vue
=> chore: flickity buttons hover and pressed style

src/popup/router/pages/CommentNew.vue
fixes #681,
or we may setInterval and check if the text changed (not a very good solution)
or we may implement more complex solution with cordova plugin that will check `deviceready` and just reload from the query text,
something like https://github.com/katzer/cordova-plugin-background-mode
=> fix(comment-new): redirect to /account on successful comment send

package-lock.json, package.json
Update to SDK 8.1.0 is needed because that version increases the compiler version validity check. As there is a compiler 6.0.0 release planned for Iris this PR should be included in order to ensure Iris compatibiity.
=> Update SDK to 8.1.0

src/popup/router/components/BalanceInfo.vue, src/popup/router/components/Dropdown.vue
Of course we should make refactoring and redesigning of dropdown (started in #1144) but this changes looks the most reasonable right now.
Before:
After:
=> style(dropdown): make dropdown wider and always on top

src/popup/router/components/BalanceInfo.vue
This fixes behavior when you click somewhere on the card in the line with dropdown and it appears.
=> fix(dropdown-width): make dropdown list width constant

src/popup/router/components/TransactionList.vue
Transaction list shows loader while not fetching because of a guard clause: https://github.com/aeternity/superhero-wallet/blob/00f6f24ac66d9b8a5ed6c185fff95ed657f18709/src/popup/router/components/TransactionList.vue#L148
=> fix(tx-list): show loader only when fetching

src/popup/router/components/ActionsMenu.vue, src/popup/router/components/BalanceInfo.vue, src/popup/router/components/Dropdown.vue, src/popup/router/components/NotificationItem.vue, src/popup/router/components/SmallModal.vue, src/popup/router/pages/Networks.vue, tests/e2e/integration/account.js
Removed deprecated stuff, that shoud've been removed in #519,
changing approx sign to a new one,
fixes #1216,
also fixes
- shifting of dropdown on large amount of tokens
- centering of dropdowns instead of aligning to the right
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/125892943-265c512d-3dc7-4edc-8317-fe5415356c92.png)|![image](https://user-images.githubusercontent.com/9008074/125893647-a88f2c63-71ab-48d9-bedb-8473a097a280.png)|
|![image](https://user-images.githubusercontent.com/9008074/125893817-a4abc336-57fc-4ec0-99ec-deca45b6c3b7.png)|![image](https://user-images.githubusercontent.com/9008074/125893853-0cc43d6a-9083-4c45-bb4b-7f5ed1b58c08.png)|
=> Refactor dropdown

src/popup/router/routes/index.js
=> fix(mobile-share): allow tip url to be passed in TipsSend

src/popup/router/pages/Retip.vue, src/store/actions.js
Fixes this behaviour on retip:
=> Fix retip url and svg

src/popup/router/components/NodeConnectionStatus.vue, src/popup/router/components/TabBar.vue, src/styles/mixins.scss
fixes #1120 
+ TabBar hidden in collapsed view as in my opinion collapsed view should be just for info reference, not complicated navigating
=> Align node status bar in collapsed iframe

src/popup/router/components/NodeConnectionStatus.vue
Fixes this issue on screens which have tab bar hidden (details, bidding):
=> fix(status): set bottom to 0 if tab bar is hidden

package-lock.json, package.json
While rebasing of #1240 I discovered that `npm i` is removing `cordova-clipboard` from `package-lock.json`. Let's add this plugin to dependencies. Also we can consider moving all cordova plugins to `devDependencies` after they will resolve issues like this: https://github.com/apache/cordova-lib/issues/832
=> feat(cordova): add cordova-clipboard to dependencies

src/popup/router/components/Modals/Confirm.vue, src/popup/router/components/Modals/Help.vue
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/9008074/132454840-8e9c6df3-ef49-4a36-a298-3253016dabd9.png)|![image](https://user-images.githubusercontent.com/9008074/132454927-de7e2fa9-ccb9-49f8-8a08-fd02c6368a65.png)|
=> fix(modal): set empty span on attribute msg undefined

src/popup/router/index.js
fixes #1271
Double slash in URL causes redirect to `not-found` on iOS and Android.
=> fix(deeplinks): build redirect route correctly

src/popup/router/components/TransactionList.vue
The problem here is that after the component being destroyed it is waiting while the code will stop working and then garbage collector will clean it, but we have two functions that are calling each other in an infinite loop. In result we have a several request being send to the mdw to get the transactions on other pages. There is a flag `_isDestroyed` which can do the same trick as i did in the PR, but since this is a private method, on the side of vue they might brake it without any documentation.
=> fix(transaction-list): do not send request after component being destroyed

config.xml, package-lock.json, package.json
This changes have been made because from 1st November, 2021 Google rejects any releases built with target sdk version lower than 30.
And because some of our Cordova plugins isn't updated for that additional plugin for converting code to android >10 was needed.
v0.9.3 android release already uploaded with this changes.
=> Build for higher target sdk version

src/background/wallet.js, src/lib/wallet.js
- The bug was introduce after updating the sdk, sdk introduced breaking change that wasn't noticed by superhero team.
https://github.com/aeternity/aepp-sdk-js/commit/12892002
- Part with iframe dissconnection wasn't working even before, since the way we destructuring the `sdk` wasn't right.
https://github.com/aeternity/superhero-wallet/commit/bc6cb3e27e73dca7c350fa353d23be5fe6b50b8a#diff-460bfcccc156ac0c09b2d513d27195dde79c25c576275509dc7d1944afdcd5b9R99
=> Disconnect connected aepps properly

src/popup/router/pages/FungibleTokens/TokenDetails.vue
missed in #1441  
fixing:
Buy AE from balances tab -  black screen - the same on dev version:
_Originally posted by @Liubov-crypto in https://github.com/aeternity/superhero-wallet/issues/1467#issuecomment-1158946998_
=> fix(token-details): add a proper link to a simplex

src/popup/locales/en.json, src/popup/router/components/NameItem.vue, src/popup/router/pages/Names/List.vue, src/store/plugins/names.js
fixes #1498,
missed in https://github.com/aeternity/superhero-wallet/pull/1428
different behaviour was introduced in https://github.com/aeternity/aepp-sdk-js/releases/tag/v10.0.0,
the `update` function started to take `pointers` param as an object
https://github.com/aeternity/aepp-sdk-js/commit/f6b8999ac70d10c5455e9a45d8ad65e161d28ca4#diff-a5a25d799d8bc055cb440014a53ac0c51693a3f56f0c7403740a64e45215f708R78
=> Adjust name item

src/mixins/deeplinkApi.js
fixes #1516,
fixes #1517,
fixes #1466
=> fix(deeplink-api): complete opening a callback url correctly

src/popup/router/components/TransactionItem.vue, src/popup/router/pages/TransactionDetails.vue, src/popup/router/pages/TransferSend.vue, src/store/mutations.js, src/store/plugins/fungibleTokens.js
Since all the dex contract calls contain user address, `txs/backward` will return them and will have more information than `aex9/transfers/to/`. I propose to exclude them from the list which `getTokenHistory` is returning.
=> Fix transactions

src/popup/components/AuctionOverview.vue, src/popup/components/InputAmountV2.vue, src/popup/components/Modals/Confirm.vue, src/popup/components/Modals/ConfirmTransactionSign.vue, src/popup/components/Modals/ErrorLog.vue, src/popup/components/Modals/Help.vue, src/popup/components/Modals/ShareQr.vue, src/popup/components/NameItem.vue, src/popup/components/NotificationItem.vue, src/popup/components/TransactionDetailsPoolTokenRow.vue, src/popup/components/TransferReviewTip.vue, src/popup/components/TransferSendForm.vue, src/popup/pages/Names/AuctionBid.vue, src/popup/pages/Popups/Connect.vue, src/popup/pages/Popups/MessageSign.vue, src/popup/pages/TransactionDetails.vue
Tech enabler for the further migration to Vue 3.
`slot="xxx"` is not working in Vue 3 and should be replaced with `<template #xxx>...</template>`.
=> [SW-302]: Vue 3 compatible way of passing content to component slots

src/store/actions.js
Basically the previous behaviour is keep increasing amount of `/` symbols in the url.
=> fix(transactions): fetch next transactions page correctly

src/popup/pages/TransactionDetailsContent.vue, src/store/actions.js
This PR:
- adding missing calim tip transaction info: `nonce`, `block height`
- using a proper type for a `to` prop in `LinkButton` using `tipUrl`
- Also handling a long tipUrl correcrtly 
|Before|After|
|--|--|
|![image](https://user-images.githubusercontent.com/9008074/204574264-6d5128f8-41bc-459a-88d7-ce2c1e609c61.png)|![image](https://user-images.githubusercontent.com/9008074/204574448-1afad2ab-6976-4352-84fe-f95a9a292ed8.png)|
=> Fix claim tip transaction info

src/popup/components/InviteItem.vue, src/popup/components/Modals/Confirm.vue, src/popup/components/Modals/ConfirmRawSign.vue, src/popup/components/Modals/ConfirmTransactionSign.vue, src/popup/components/Modals/ErrorLog.vue, src/popup/components/Modals/ResetWallet.vue, src/popup/components/Modals/SpendSuccess.vue, src/popup/components/Modals/TransferSend.vue, src/popup/components/buttons/BtnMain.vue, src/popup/pages/Dashboard.vue, src/popup/pages/DonateError.vue, src/popup/pages/Index.vue, src/popup/pages/NetworkForm.vue, src/popup/pages/Networks.vue, src/popup/pages/PermissionManager.vue, src/popup/pages/PermissionsSettings.vue, src/popup/pages/Popups/Connect.vue, src/popup/pages/Popups/MessageSign.vue, src/popup/pages/SeedPhraseDetailsSettings.vue, src/styles/variables.scss
As mentioned in a [comment](https://github.com/aeternity/superhero-wallet/pull/1730#discussion_r1046891038) in PR related to [SW-42](https://github.com/aeternity/superhero-wallet/pull/1730):
- Newly introduced color (`#ff4746`) will be used as `$color-danger`. So from now on all "danger" places will use it.
- The color that we actually use as the "danger" (`#ff2b5e`) should be moved to the new variable `$color-secondary.`
- The `BtnMain` `variant="secondary"` should use instead of gray the color `$color-secondary` (the pink).
- The old secondary variant of `BtnMain` should be replaced with muted. Please remember to align every occurance of the `BtnMain` with `variant="secondary"` prop.
=> Refactor: adjust button variants and colours to new style guide

cypress.json, src/popup/components/Modals/SpendSuccess.vue, src/popup/components/Modals/TransferSend.vue, src/popup/components/TransferReview.vue, src/popup/components/TransferSendForm.vue, src/popup/locales/en.json, src/popup/pages/Dashboard.vue, src/popup/utils/config.js, tests/e2e/integration/withdraw.js, tests/e2e/support/commands.js
- on reviewing #1727, found out an error that could've been intercepted by this disabled test,
- our automated tests were overloading `api.coingecko` and it was throwing `429 (Too Many Requests)`, which resulting in a broken `balances` composable (#1782)
=> [SW-586] Enable withdraw test

src/composables/transaction.ts
=> fix: set correct labels for a spend transactions

src/composables/multisigAccounts.ts, src/popup/pages/MultisigDetails.vue, src/popup/pages/MultisigProposalDetails.vue
Table of dry runs called every 7 seconds
**with additional info** means that some pages demand additional info (`MultisigDetails`, `MultisigProposalDetails`), but we will have one more dry-run and only for active account
|Multisig info|Before|After (with additional info)|After (without additional info)|
|---|---|---|---|
|1 visible vault|**3** dry-runs | **2** dry-runs|**1** dry-run|
|10 visible vaults|**30** dry-runs | **11** dry-runs|**10** dry-runs|
=> [SW-636] Improve multisig performance

src/popup/components/Modals/MultisigVaultCreate.vue
The m of n selection used to fail when the current confirmations required value becomes larger than the signers length. This fix ensures that the confirmations required is set to signers length
=> [SW-634] Fix confirmations required value in m of n signers selection

src/popup/components/FungibleTokens/TokensListItem.vue, src/popup/components/Modals/AssetSelector.vue
=> [SW-699] fix: show asset selector correctly on firefox

src/popup/components/InputField.vue
Needed to remove the native browser input validation cause it's causing issues for Safari & Firefox
we already have custom logic for validating number withing `<InputField` `checkIfNumber` so this removal is safe
=> [SW-719] firefox & safari input validation

src/popup/utils/utils.ts
=> [SW-746] fix: fetch all endpoint pages correctly

src/popup/components/TransferSendForm.vue
Functionality that is requested in #2041, #2042 can be implemented in this way. So we would be able get `payload` from query same as other parameters: `amount`, `token`, `account`.
https://feature-handle-payload-in-send-modal-query.wallet.z52da5wt.xyz/account?account=ak_zmzmiPdG7mgppzh2Kb9wpm8MWgJTpdarRtF8EYhsPG7UbQ3Yh&token=AE&amount=11&payload=test
=> feat(send-modal): handle payload in query

src/popup/pages/Names/Auction.vue
In order to check this PR you need to find, or to start auction for a name that expired. Now it is easy to check on `ae86.chain` name on mainnet.
https://github.com/aeternity/ae_mdw/issues/1294
=> [SW-896] fix: show auctions for an existing name correctly

src/popup/components/tabs/Tab.vue
Moved exact prop functionality to be handled manually
For more info: https://router.vuejs.org/guide/migration/#removal-of-the-exact-prop-in-router-link
=> fix: replace vue router exact prop

src/lib/logger.ts
part of #1799 
- `warnHandler` is ignored in production mode, saving logs in the dev mode is pointless https://vuejs.org/api/application.html#app-config-warnhandler
- current implementation of `warnHandler` function results in infinite loop of warnings and saving them to the logs (which cause 100% core usage)
=> [SW-905] fix: do not save warnings in develop mode

config.xml
Removed preferences from `config.xml` . Already added new configuration at initial commit of `feature/migrate-to-ionic` branch
=> [SW-946] refactor: remove splash screen preferences from config file

config.xml, package-lock.json, package.json
This plugin seems to be obsolete in "newer" android versions (iOS was never supported). Check its functionality [here](https://github.com/tomloprod/cordova-plugin-headercolor)
Also, there is no capacitor replacement for this plugin
=> [SW-947] feature/remove cordova headercolor plugin

package-lock.json, package.json, src/composables/index.ts, src/composables/sdk13.ts, src/composables/tippingContracts.ts, src/lib/contracts/TippingV1ACI.json, src/lib/contracts/TippingV2ACI.json, src/lib/wallet.js, src/popup/components/TransferReview.vue, src/popup/pages/Retip.vue, src/popup/pages/TipsClaim.vue, src/popup/utils/constants.ts, src/store/actions.js, src/store/index.js, src/store/mutations.js, src/types/index.ts
- also it slightly speeds up e2e tests, `other` in particular.
- fix spelling error https://github.com/aeternity/tipping-contract/pull/11, https://github.com/aeternity/tipping-contract/pull/11/commits/9d5df2c89ed81947dd423ed250511acf745a1ec2
=> [SW-969] perf: initialize tipping contracts only if needed

src/store/plugins/sdk.js
`getters.activeNetwork` was never calling the watcher cb.
I'm not sure if this is an issue with the new Vue or Vuex version but it seems the SDK (or Vuex) is behaving problematic now.
This is more of a workaround than a permanent fix but since we are planning to replace both the store and old version of the SDK I believe this should be ok.
=> fix: issue with network sync

package.json
`npm run watch` wasn't working after updating to `webpack@5.x` because when run in development mode it uses `eval` for source-maps. 
Building & rebuilding with this command is now slower as it builds for production.
Configuring webpack `devtool` to not use `eval` for source-maps is equally slow.
=> fix: webpack error with watch

src/composables/latestTransactionList.ts, src/popup/components/TransactionListItem.vue
I see the latest transaction widget is not shown when there is no pending transaction or there is no balance/network change. 
The wallet doesn't show confirmed past transactions. Hence on load, fetch past transactions once.
=> Fetch confirmed transactions on load

src/composables/aeSdk.ts, src/popup/components/TransactionInfo.vue, src/popup/components/TransactionInfoDetailsParty.vue, src/popup/locales/cn.json, src/popup/locales/de.json, src/popup/locales/en.json, src/popup/locales/es.json, src/popup/locales/fr.json, src/popup/locales/it.json, src/popup/locales/ru.json, src/popup/pages/PermissionManager.vue, src/popup/pages/Popups/AccountList.vue, src/popup/router/index.ts, src/popup/router/modals.ts, src/popup/router/routes.ts, src/popup/router/webIframePopups.ts, src/popup/utils/constants.ts, src/popup/utils/testsConfig.ts, src/store/modules/permissions.js, src/types/index.ts, tests/e2e/integration/aex2-popups.js
You need an aepp requesting all account addresses to test this. I have deployed one.
1. use the extension from this artifact
2. visit aepp https://subhod-i.github.io/ 
3. click 'Connect', First aepp will request for typical connection popup and then the second popup is where it is requesting all the account addresses. See if it is according to the design and test by toggling the new permission settings.
=> [SW-901] Add popup for aepps requesting all account addreseses

src/composables/accounts.ts, src/composables/balances.ts, src/lib/ProtocolAdapterFactory.ts, src/protocols/BaseProtocolAdapter.ts, src/protocols/aeternity/libs/AeternityAdapter.ts, src/protocols/bitcoin/libs/BitcoinAdapter.ts, src/store/getters.js, src/store/modules/accounts/hdWallet.js, src/store/modules/accounts/index.js, src/types/index.ts
Approach
1. add new property `protocol` for `IAccount` which holds the account chain. Added default `aeternity` to existing accounts
2. Define interface `IProtocol` with common chain operations
3. Implement `AeternityProtocol, BitcoinProtocol, DogecoinProtocol implements IProtocol`  
4. Define a new composable `sdk.ts` which is crucial and exposes the Protocol instances to the project
5. Use `getSdk` method to send coins and to get the account address balance.
=> [SW-1019] Implement multichain protocol interface

src/composables/transactionTx.ts, src/popup/router/index.ts, src/popup/utils/index.ts, src/utils/getPopupProps.ts, src/utils/i18nTranslations.ts, src/utils/index.ts
This is 2nd approach for merging the same change as it turns out the previous one are not present in the feature branch. The previous PR is here: https://github.com/aeternity/superhero-wallet/pull/2225
=> Refactor:  Move last popup utils to global utils dir

package-lock.json, package.json, src/popup/components/InviteItem.vue, src/popup/pages/Invite.vue, src/popup/pages/InviteClaim.vue, src/popup/router/routes.ts, src/store/migrations/07-change-invite-links-format.js, src/store/migrations/index.js, src/store/modules/invites.js
=> [SW-1183] feat: adjust invite links

src/popup/components/Header.vue, src/popup/router/index.ts
In-app browser feature is mobile only so we want to hide it from other platforms.
**Note:** should only be merged when #2242 is tested and is ready to be merged.
=> feat: make in-app browser feature mobile-only

.github/workflows/main.yml
- https://github.com/actions/create-release is no longer maintained.
- Wallet were using deprecated commands via outdated actions https://github.com/aeternity/superhero-wallet/actions/runs/6224561419/job/16893035132#step:13:11
=> ci: do not use deprecated commands in actions

src/constants/common.ts, src/popup/App.vue, src/popup/animations/fade.ts, src/popup/animations/index.ts, src/popup/animations/popIn.ts, src/popup/animations/popOut.ts, src/popup/components/AccountDetailsBase.vue, src/popup/components/DefaultPagesRouter.vue, src/popup/components/Header.vue, src/popup/pages/FungibleTokens/TokenContainer.vue, src/popup/pages/Names/Auction.vue, src/protocols/aeternity/views/AccountDetailsNames.vue
closes #2420 
Replace default animations when opening/closing `account-details` and when switching tabs
=> feat: replace default animations

src/popup/pages/Names/NamesList.vue
closes #2599 
`onIonViewWillLeave` was only being called when user switched from `My names` to other sub-tabs `Auctions` & `Register name`.
When user closed the `account-details` page it was not being called, leaving an unterminated interval.
`onUnmount` will be called when user closes the `account-details` page, which means that while user is on that page, names will update every 10 seconds. But when he leaves this page names will stop updating.
=> fix: owned names should only be updated for current network

src/popup/components/Modals/QrCodeReader.vue
This is related to the issue #2576 but is not fixing it.
This PR improves scanning on mobile devices with Safari so I suggest to merge it independently
=> fix: qr scanner on safari mobile

src/popup/pages/PermissionManager.vue
closes #2621 
by using `replace` ionic will not cache the page component and previous permission will not be shown after being deleted
=> fix: dont allow ionic to cache permission manager page

src/popup/components/SeedPhraseNotification.vue, src/popup/pages/SeedPhraseVerifySettings.vue
closes #2626 
Size of the `phraser` element can change if words in seed-phrase are more & bigger. With this change no matter how the big the element is the notification element will always match it pixel perfect
=> fix: seed-phrase verification alert alignment

src/popup/components/AddressTruncated.vue, src/popup/components/TransactionOverview.vue, src/protocols/aeternity/libs/AeScan.ts, src/protocols/ethereum/libs/EtherscanExplorer.ts
Explorer links were wrong because for Aeternity/AeScan we can determine what endpoint to use and we were using `prepareUrlForHash` everywhere, which doesn't work for Ethereum and Bitcoin
=> fix: eth account explorer links

android/app/src/main/AndroidManifest.xml
The original issue is probably fixed already as the app links seem to be working fine
This PR just adds support for http links
closes #1980
=> fix: delegate http applinks to https

src/constants/common.ts, src/popup/components/AccountItem.vue, src/popup/components/IconWrapper.vue, src/popup/components/Modals/NetworkSwitcherModal.vue, src/popup/components/ProtocolIcon.vue, src/popup/components/Tokens.vue, src/popup/components/TransactionListItem.vue, src/popup/components/TransactionTokenRows.vue, src/popup/components/buttons/BtnMain.vue, src/popup/pages/MultisigProposalDetails.vue, src/protocols/aeternity/views/TransactionDetails.vue, src/protocols/bitcoin/views/TransactionDetails.vue, src/protocols/ethereum/views/TransactionDetails.vue, src/styles/global.scss, tests/unit/__snapshots__/snapshot.spec.js.snap
closes #2578 
_Based on `eth-support` because there were some changes with icons but could be rebased on develop as well if needed._ 
I think having a global standard for icon sizes will help cross-component compatibility (e.g. `ProtocolIcon.vue` inside `Tokens.vue`)
One shortcoming of this approach is that some components do not have `rg` as the default size (which semantically makes sense) but I think that the clarity of the global standard is more important
=> refactor: unify icon sizes

src/popup/components/AccountDetailsBase.vue, src/popup/pages/AccountDetailsMultisig.vue, src/protocols/aeternity/views/AccountDetails.vue, src/protocols/bitcoin/views/AccountDetails.vue
closes #2572 
closes #2563
As much as I hate using this `ionicLifecycleStatus` prop, it is the best way to achieve what we're trying to do. Which is to calculate the tabs-height after the page transition has played. `onIonViewDidEnter` fires at exactly that moment but isn't directly available to the `AccountDetailsBase` component thus we pass it as a prop.
Using the timeout didn't always work correctly because depending on the user's machine the animation can take longer or even not play at all (e.g. animations are disabled on FF or user visits the page directly)
=> fix: transaction list is displaying partly

src/composables/accounts.ts
closes #2713 
Even though the actual migration was not being called because of the inner if check, it was still causing issues with the extension
=> fix: do not call cordova mnemonic migration on extension

src/popup/router/routes.ts, src/protocols/aeternity/views/TransactionDetails.vue, src/protocols/bitcoin/views/TransactionDetails.vue, src/protocols/ethereum/views/TransactionDetails.vue
fixes:
> 8. After sending ERC-20 tokens Txs I clicked on Tx to see Tx details, but the page hang out and I find these issues in console:
from #2736 
If we reach the API limit and can't fetch details for a tx we're redirected to the 404 page. 
This wasn't working properly because we didn't have a specific 404 page path and were trying to display the 404 page at `/`
Now we redirect unknown pages to `/page-not-found`
Also disables the loader before redirecting
=> fix: redirect to 404 when tx cant be fetched

src/utils/common.ts
fixes 
```
Must be called at the top of a `setup` function
SyntaxError: Must be called at the top of a `setup` function
at createCompileError (webpack-internal:///./node_modules/@intlify/message-compiler/dist/message-compiler.esm-browser.js:113:19)
at createI18nError (webpack-internal:///./node_modules/vue-i18n/dist/vue-i18n.mjs:115:82)
at useI18n (webpack-internal:///./node_modules/vue-i18n/dist/vue-i18n.mjs:2316:15)
at secondsToRelativeTime (webpack-internal:///./src/utils/common.ts:528:68)
at blocksToRelativeTime (webpack-internal:///./src/utils/common.ts:234:10)
at eval (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/ts-loader/index.js??clonedRuleSet-44.use[1]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/popup/pages/MultisigProposalDetai …
```
=> fix: do not use useI18n outside the setup function

src/popup/components/AssetIcon.vue, src/popup/components/ProtocolIcon.vue, src/popup/components/TransferSend/TransferSendAmount.vue, src/popup/plugins/veeValidate.ts
fixes emit and prop validation issues
```
logger.ts:50 Invalid prop: custom validator check failed for prop "iconSize". at <AssetIcon>
at <Tokens>
[Vue warn]: Component emitted event "asset-selected" but it is neither declared in the emits option nor as an "onAsset-selected" prop.
```
Also fixes this issue on custom network creation
```
veeValidate.ts:114 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toString')
```
=> fix: validate several props and emits correctly

src/popup/components/AppsBrowser/AppsBrowserHeader.vue, src/popup/components/Modals/WarningDappBrowser.vue
resolves button & apps browser props validation warning
=> refactor: apps browser props validation

src/composables/maxAmount.ts, src/popup/components/Modals/ConfirmTransactionSign.vue
=> fix: use correct nonce to dry-run contract calls

src/protocols/aeternity/libs/AeternityAdapter.ts
This was our previous behaviour, it was lost in the process of restructuring of the project.
=> refactor(aeternity): do not wait transaction mining to finalize transfer

src/protocols/ethereum/helpers/index.ts, src/protocols/ethereum/libs/EthereumAdapter.ts, src/protocols/ethereum/views/TransactionDetails.vue
fixed #2789 
Also removes timestamp and block number from pending transactions 
(`getBlock` will return a block even if `blockHash` is missing)
=> fix: show correct details for pending ethereum transactions

src/composables/aeSdk.ts, src/composables/multisigAccounts.ts
fixing one part of the issue raised here
https://github.com/superhero-com/superhero-wallet/blob/d233c480fcbc0a0ab1ddf79deda42b30d96495c5/src/protocols/aeternity/libs/AeSdkSuperhero.ts#L35
by simply using `dryRunSdk` that doesn't have accounts and will not call our overridden `_resolveAccount` method, every time we are updating multisig vaults info.
=> perf: use dryAeSdk to collect multisig info

src/popup/components/Modals/ConfirmTransactionSign.vue, src/popup/locales/en.json, src/popup/pages/SignTransaction.vue, src/types/index.ts
the idea here is to be able to prepare a transaction externally without knowing who will execute it (i.e. to save an additional step to get account via deeplink callback)
=> feat: allow replace caller in sign transaction

src/protocols/bitcoin/libs/BitcoinAdapter.ts
closes #3003 
We're setting the default values for custom networks to be testnet related, but we were using mainnet BTC addresses on them
=> fix: custom networks are testnet type

src/background/index.ts
This PR fixes 2 issues that happens in the chrome extension's background process.
1. "window is not defined" - happening because we are including the polyfills for the browser which attempts to add the `browser` into `window` object, which does not exist in the background process.
2. "Only a single offscreen document may be created." - happening because we are running `browser.runtime.getURL` twice.
=> fix: remove window browser polyfill from ext background

src/composables/multisigAccounts.ts, src/protocols/aeternity/types.ts
fixes https://github.com/superhero-com/superhero-wallet/issues/3092
Idea of this PR is to split all the multisig vaults into array of fives. And only dry-run five vault information in parallel.
=> Improve multisig performance

src/types/index.ts
Not sure why @konradodo added this type here: https://github.com/superhero-com/superhero-wallet/pull/2306/files#diff-a9ba9cbedd19c9f66d564d2e89912890209b98f0a7ef19187877d2587300e476R451
But as far as I see it's not used because the `ITx` has a `type` property with `TxType` type.
=> refactor: remove transaction type property

src/composables/walletConnect.ts
https://specs.walletconnect.com/2.0/specs/clients/sign/namespaces#210-session-namespaces-must-approve-all-events
fixes #3217
=> fix(wallet-connect): approve all required events

src/popup/App.vue, src/popup/router/routes.ts
The `Header` was not displayed if the `hideHeader` parameter in the `route.meta` was set to `true`, but in this case notification polling was started (initial calculation of Header that required `notification` composable was done).
=> Improve `showHeader` logic

src/popup/locales/en.json, src/popup/pages/Index.vue
=> refactor: update Index page wording

src/composables/transactionData.ts
=> fix: show token sale label only for token sale transactions

src/popup/components/Modals/ConfirmTransactionSign.vue, src/popup/components/PanelTableItem.vue, src/popup/components/TransactionCallDataDetails.vue, src/protocols/ethereum/helpers/index.ts, src/protocols/ethereum/libs/EthereumAdapter.ts, src/protocols/ethereum/libs/EtherscanService.ts, src/protocols/ethereum/views/TransactionDetails.vue, tests/unit/__snapshots__/snapshot.spec.js.snap
closes #3097 
closes #3096 
Show user decoded data (if possible, if not show raw data) in transaction details so that he can figure out what the contract call did. This does not exactly solve the issues but seems like the best solution. Etherscan also only shows the decoded data since it would be impossible to create resolvers/parsers for every contract out there
=> feat: show decoded call data on eth tx details

src/popup/components/form/FormAccountInput.vue
=> fix: missing warning message when focusing/unfocusing autocomplete input

src/composables/deepLinkApi.ts
=> fix: auto-sign not redirecting back to browser

src/composables/addressBook.ts, src/composables/modals.ts, src/constants/common.ts, src/lib/logger.ts, src/popup/components/AddressBook/AddressBookList.vue, src/popup/components/InputField.vue, src/popup/components/Modals/ConfirmDisableErrorLog.vue, src/popup/components/Modals/ErrorLog.vue, src/popup/components/Modals/MultisigVaultCreate.vue, src/popup/components/buttons/BtnSubheader.vue, src/popup/locales/en.json, src/popup/pages/ErrorLogSettings.vue, src/popup/pages/SignTransaction.vue, src/popup/router/modals.ts, src/protocols/aeternity/components/TransferReview.vue, src/protocols/aeternity/components/TransferSignedTxReview.vue, src/protocols/aeternity/libs/AeAccountHdWallet.ts, src/protocols/bitcoin/components/TransferReview.vue, src/protocols/ethereum/components/TransferReview.vue, src/utils/common.ts
closes: #3039 
- Reusable export method for downloading files
- Changed wording in Error log Settings screen
- New modal to confirm disabling the logs
- Improved error logging on Transfers + Signing
- Error modal with Export button in the above cases
- Small UI fixes on buttons and inputs
=> feat: export error log and show error modals on transaction errors

src/composables/aeSdk.ts
=> fix(aeternity): share wallet info with dapp

ios/App/App/Info.plist
- Added a new property in Info.plist to manage the encryption compliance in Testflight without the need to access AppStoreConnect on every build
=> fix: ios missing compliance

src/popup/locales/en.json, src/popup/pages/Popups/ConnectBase.vue
closes: #3448 
On Disconnect the `rememberMe` permission should be set to false automatically, but there seems to be an issue with the SDK. The `onDisconnect` method is not called properly, so this will not be implemented at this stage.
=> feat: wallet connect remember me checkbox

src/composables/accounts.ts, src/popup/App.vue, src/popup/components/AccountCard.vue, src/popup/components/AccountInfo.vue, src/popup/components/AccountSelectOptionsItem.vue, src/popup/components/AddressBook/AddressBookList.vue, src/popup/components/FormSelectOptionsHeader.vue, src/popup/components/Modals/AccountSelectOptions.vue, src/popup/components/PanelItem.vue, src/popup/components/form/FormSelect.vue, src/popup/locales/en.json, src/popup/pages/Popups/ConnectBase.vue
closes: #3449
also fixes a UI issue on wallet connect popup's dimensions
=> feat: change active account on dapp login

src/composables/fungibleTokens.ts, src/composables/transactionData.ts, src/constants/common.ts, src/popup/components/Modals/ConfirmTransactionSign.vue, src/popup/components/TransactionLabel.vue, src/popup/components/TransactionTagList.vue, src/popup/locales/en.json, src/protocols/aeternity/composables/aeMiddleware.ts, src/protocols/aeternity/composables/aeTokenSales.ts, src/protocols/aeternity/config.ts, src/protocols/aeternity/helpers/index.ts, src/protocols/aeternity/helpers/transactionTokenInfoResolvers.ts, src/protocols/aeternity/libs/AeternityAdapter.ts, src/protocols/aeternity/views/TransactionDetails.vue, src/types/index.ts, src/utils/common.ts
fixes #3387,
fixes #3460,
fixes #3464,
fixes #3465,
fixes #3417,
This PR is missing one particular case, if the user will refresh the Transaction Details for a `buy` token sale transaction, the info become less informative (and untruthful to spend amount and to received tokens/missing protocol token) .
After this issue will be resolved it will be easy from our side to fix that https://github.com/aeternity/ae_mdw/issues/2075
=> Enrich token sale transactions information

src/popup/components/Tokens.vue, src/popup/components/TransactionAssetRows.vue, src/protocols/aeternity/helpers/transactionTokenInfoResolvers.ts, src/protocols/aeternity/views/TransactionDetails.vue, src/utils/common.ts
- fixes #3406,
- fixes #2647,
- fixes issue when token sale transaction is in the latest transaction widget have full info, but clicking on leads you to the transaction details page with less info (not enriched info). 
- enriches `createCommunity` contact call info
=> Adjust transaction list

src/composables/aeSdk.ts, src/composables/permissions.ts, src/composables/walletConnect.ts, src/content-scripts/inject.ts, src/content-scripts/inpage.ts, src/popup/pages/Popups/MessageSign.vue, src/popup/router/index.ts, src/protocols/ethereum/config.ts, src/protocols/ethereum/libs/EthereumRpcMethodsHandler.ts, src/protocols/ethereum/libs/EtherscanService.ts, src/protocols/ethereum/types.ts
=> EVM improvements
